import type { Position, Continent } from "../types";

export const PERSONALITIES: string[] = [
  "Ambitious",
  "Lazy",
  "Professional",
  "Temperamental",
  "Loyal",
  "Determined",
  "Media Darling",
  "Reserved",
  "Inconsistent",
];

export const POSITIONS: Position[] = [
  "Attacker",
  "Midfielder",
  "Defender",
  "Goalkeeper",
];

export const CONTINENTS: Continent[] = [
  "Europe",
  "South America",
  "Africa",
  "Asia",
  "North America",
  "Australia",
];

export const continentToCountries: { [key in Continent]: string[] } = {
  Europe: [
    "England",
    "Spain",
    "Germany",
    "Italy",
    "France",
    "Netherlands",
    "Portugal",
    "Turkey",
  ],
  "South America": ["Brazil", "Argentina", "Colombia", "Uruguay"],
  Asia: ["Saudi Arabia", "Japan", "South Korea"],
  Africa: ["Egypt", "Morocco"],
  "North America": ["USA", "Mexico"],
  Australia: ["Australia"],
};

// Rankings FIFA Novembro 2025 - Dados Oficiais Completos (210 países)
export const NATIONALITIES = [
  // ========== EUROPA (UEFA) ==========
  { name: "Spain", continent: "Europe", fifaRank: 1, talentPool: 98 },
  { name: "France", continent: "Europe", fifaRank: 3, talentPool: 97 },
  { name: "England", continent: "Europe", fifaRank: 4, talentPool: 95 },
  { name: "Portugal", continent: "Europe", fifaRank: 6, talentPool: 91 },
  { name: "Netherlands", continent: "Europe", fifaRank: 7, talentPool: 92 },
  { name: "Belgium", continent: "Europe", fifaRank: 8, talentPool: 90 },
  { name: "Germany", continent: "Europe", fifaRank: 9, talentPool: 93 },
  { name: "Croatia", continent: "Europe", fifaRank: 10, talentPool: 87 },
  { name: "Italy", continent: "Europe", fifaRank: 12, talentPool: 92 },
  { name: "Switzerland", continent: "Europe", fifaRank: 17, talentPool: 84 },
  { name: "Denmark", continent: "Europe", fifaRank: 21, talentPool: 85 },
  { name: "Austria", continent: "Europe", fifaRank: 24, talentPool: 82 },
  { name: "Turkey", continent: "Europe", fifaRank: 25, talentPool: 80 },
  { name: "Ukraine", continent: "Europe", fifaRank: 28, talentPool: 79 },
  { name: "Norway", continent: "Europe", fifaRank: 29, talentPool: 78 },
  { name: "Poland", continent: "Europe", fifaRank: 31, talentPool: 80 },
  { name: "Wales", continent: "Europe", fifaRank: 32, talentPool: 75 },
  { name: "Russia", continent: "Europe", fifaRank: 33, talentPool: 78 },
  { name: "Scotland", continent: "Europe", fifaRank: 36, talentPool: 76 },
  { name: "Serbia", continent: "Europe", fifaRank: 37, talentPool: 81 },
  { name: "Hungary", continent: "Europe", fifaRank: 41, talentPool: 76 },
  { name: "Sweden", continent: "Europe", fifaRank: 43, talentPool: 83 },
  { name: "Czech Republic", continent: "Europe", fifaRank: 44, talentPool: 77 },
  { name: "Slovakia", continent: "Europe", fifaRank: 45, talentPool: 75 },
  { name: "Greece", continent: "Europe", fifaRank: 46, talentPool: 73 },
  { name: "Romania", continent: "Europe", fifaRank: 47, talentPool: 74 },
  { name: "Slovenia", continent: "Europe", fifaRank: 55, talentPool: 74 },
  { name: "Ireland", continent: "Europe", fifaRank: 59, talentPool: 72 },
  { name: "Albania", continent: "Europe", fifaRank: 63, talentPool: 72 },
  {
    name: "North Macedonia",
    continent: "Europe",
    fifaRank: 65,
    talentPool: 68,
  },
  {
    name: "Northern Ireland",
    continent: "Europe",
    fifaRank: 69,
    talentPool: 65,
  },
  {
    name: "Bosnia and Herzegovina",
    continent: "Europe",
    fifaRank: 71,
    talentPool: 74,
  },
  { name: "Georgia", continent: "Europe", fifaRank: 73, talentPool: 70 },
  { name: "Iceland", continent: "Europe", fifaRank: 74, talentPool: 68 },
  { name: "Finland", continent: "Europe", fifaRank: 75, talentPool: 72 },
  { name: "Israel", continent: "Europe", fifaRank: 77, talentPool: 68 },
  { name: "Kosovo", continent: "Europe", fifaRank: 80, talentPool: 65 },
  { name: "Montenegro", continent: "Europe", fifaRank: 83, talentPool: 70 },
  { name: "Bulgaria", continent: "Europe", fifaRank: 88, talentPool: 68 },
  { name: "Belarus", continent: "Europe", fifaRank: 99, talentPool: 60 },
  { name: "Luxembourg", continent: "Europe", fifaRank: 103, talentPool: 55 },
  { name: "Armenia", continent: "Europe", fifaRank: 106, talentPool: 62 },
  { name: "Kazakhstan", continent: "Europe", fifaRank: 115, talentPool: 58 },
  { name: "Faroe Islands", continent: "Europe", fifaRank: 125, talentPool: 50 },
  { name: "Azerbaijan", continent: "Europe", fifaRank: 127, talentPool: 55 },
  { name: "Cyprus", continent: "Europe", fifaRank: 128, talentPool: 52 },
  { name: "Estonia", continent: "Europe", fifaRank: 130, talentPool: 52 },
  { name: "Latvia", continent: "Europe", fifaRank: 140, talentPool: 50 },
  { name: "Lithuania", continent: "Europe", fifaRank: 146, talentPool: 48 },
  { name: "Moldova", continent: "Europe", fifaRank: 158, talentPool: 45 },
  { name: "Malta", continent: "Europe", fifaRank: 161, talentPool: 42 },
  { name: "Andorra", continent: "Europe", fifaRank: 172, talentPool: 35 },
  { name: "Liechtenstein", continent: "Europe", fifaRank: 205, talentPool: 30 },
  { name: "Gibraltar", continent: "Europe", fifaRank: 202, talentPool: 28 },
  { name: "San Marino", continent: "Europe", fifaRank: 210, talentPool: 20 },

  // ========== AMÉRICA DO SUL (CONMEBOL) ==========
  {
    name: "Argentina",
    continent: "South America",
    fifaRank: 2,
    talentPool: 96,
  },
  { name: "Brazil", continent: "South America", fifaRank: 5, talentPool: 97 },
  {
    name: "Colombia",
    continent: "South America",
    fifaRank: 13,
    talentPool: 86,
  },
  { name: "Uruguay", continent: "South America", fifaRank: 16, talentPool: 88 },
  { name: "Ecuador", continent: "South America", fifaRank: 23, talentPool: 79 },
  {
    name: "Paraguay",
    continent: "South America",
    fifaRank: 39,
    talentPool: 75,
  },
  {
    name: "Venezuela",
    continent: "South America",
    fifaRank: 48,
    talentPool: 72,
  },
  { name: "Peru", continent: "South America", fifaRank: 52, talentPool: 76 },
  { name: "Chile", continent: "South America", fifaRank: 53, talentPool: 82 },
  { name: "Bolivia", continent: "South America", fifaRank: 76, talentPool: 65 },

  // ========== AMÉRICA DO NORTE/CENTRAL (CONCACAF) ==========
  { name: "USA", continent: "North America", fifaRank: 14, talentPool: 85 },
  { name: "Mexico", continent: "North America", fifaRank: 15, talentPool: 87 },
  { name: "Canada", continent: "North America", fifaRank: 27, talentPool: 78 },
  { name: "Panama", continent: "North America", fifaRank: 30, talentPool: 71 },
  {
    name: "Costa Rica",
    continent: "North America",
    fifaRank: 49,
    talentPool: 74,
  },
  {
    name: "Honduras",
    continent: "North America",
    fifaRank: 64,
    talentPool: 68,
  },
  { name: "Jamaica", continent: "North America", fifaRank: 70, talentPool: 70 },
  { name: "Curaçao", continent: "North America", fifaRank: 82, talentPool: 60 },
  { name: "Haiti", continent: "North America", fifaRank: 84, talentPool: 64 },
  {
    name: "Guatemala",
    continent: "North America",
    fifaRank: 94,
    talentPool: 62,
  },
  {
    name: "Trinidad and Tobago",
    continent: "North America",
    fifaRank: 98,
    talentPool: 58,
  },
  {
    name: "El Salvador",
    continent: "North America",
    fifaRank: 100,
    talentPool: 65,
  },
  {
    name: "Suriname",
    continent: "North America",
    fifaRank: 123,
    talentPool: 52,
  },
  {
    name: "Nicaragua",
    continent: "North America",
    fifaRank: 132,
    talentPool: 48,
  },
  {
    name: "Dominican Republic",
    continent: "North America",
    fifaRank: 143,
    talentPool: 45,
  },
  { name: "Guyana", continent: "North America", fifaRank: 150, talentPool: 42 },
  {
    name: "St Kitts and Nevis",
    continent: "North America",
    fifaRank: 154,
    talentPool: 40,
  },
  {
    name: "Puerto Rico",
    continent: "North America",
    fifaRank: 156,
    talentPool: 38,
  },
  {
    name: "Grenada",
    continent: "North America",
    fifaRank: 164,
    talentPool: 36,
  },
  {
    name: "Antigua and Barbuda",
    continent: "North America",
    fifaRank: 165,
    talentPool: 35,
  },
  { name: "Cuba", continent: "North America", fifaRank: 166, talentPool: 45 },
  {
    name: "St Lucia",
    continent: "North America",
    fifaRank: 167,
    talentPool: 34,
  },
  {
    name: "Bermuda",
    continent: "North America",
    fifaRank: 169,
    talentPool: 32,
  },
  {
    name: "St Vincent and the Grenadines",
    continent: "North America",
    fifaRank: 171,
    talentPool: 30,
  },
  { name: "Belize", continent: "North America", fifaRank: 181, talentPool: 28 },
  {
    name: "Dominica",
    continent: "North America",
    fifaRank: 183,
    talentPool: 26,
  },
  { name: "Aruba", continent: "North America", fifaRank: 191, talentPool: 25 },
  {
    name: "Cayman Islands",
    continent: "North America",
    fifaRank: 195,
    talentPool: 24,
  },
  {
    name: "Barbados",
    continent: "North America",
    fifaRank: 178,
    talentPool: 30,
  },
  {
    name: "Bahamas",
    continent: "North America",
    fifaRank: 206,
    talentPool: 22,
  },
  {
    name: "Turks and Caicos Islands",
    continent: "North America",
    fifaRank: 204,
    talentPool: 20,
  },
  {
    name: "US Virgin Islands",
    continent: "North America",
    fifaRank: 207,
    talentPool: 18,
  },
  {
    name: "British Virgin Islands",
    continent: "North America",
    fifaRank: 208,
    talentPool: 16,
  },
  {
    name: "Anguilla",
    continent: "North America",
    fifaRank: 209,
    talentPool: 15,
  },
  {
    name: "Montserrat",
    continent: "North America",
    fifaRank: 175,
    talentPool: 20,
  },

  // ========== ÁFRICA (CAF) ==========
  { name: "Morocco", continent: "Africa", fifaRank: 11, talentPool: 85 },
  { name: "Senegal", continent: "Africa", fifaRank: 19, talentPool: 84 },
  { name: "Egypt", continent: "Africa", fifaRank: 34, talentPool: 80 },
  { name: "Algeria", continent: "Africa", fifaRank: 35, talentPool: 79 },
  { name: "Nigeria", continent: "Africa", fifaRank: 38, talentPool: 82 },
  { name: "Tunisia", continent: "Africa", fifaRank: 40, talentPool: 76 },
  { name: "Ivory Coast", continent: "Africa", fifaRank: 42, talentPool: 81 },
  { name: "Mali", continent: "Africa", fifaRank: 54, talentPool: 75 },
  { name: "DR Congo", continent: "Africa", fifaRank: 56, talentPool: 74 },
  { name: "Cameroon", continent: "Africa", fifaRank: 57, talentPool: 79 },
  { name: "South Africa", continent: "Africa", fifaRank: 61, talentPool: 72 },
  { name: "Burkina Faso", continent: "Africa", fifaRank: 62, talentPool: 73 },
  { name: "Cape Verde", continent: "Africa", fifaRank: 68, talentPool: 68 },
  { name: "Ghana", continent: "Africa", fifaRank: 72, talentPool: 77 },
  { name: "Gabon", continent: "Africa", fifaRank: 78, talentPool: 65 },
  { name: "Guinea", continent: "Africa", fifaRank: 81, talentPool: 70 },
  { name: "Uganda", continent: "Africa", fifaRank: 85, talentPool: 62 },
  { name: "Angola", continent: "Africa", fifaRank: 89, talentPool: 60 },
  { name: "Zambia", continent: "Africa", fifaRank: 90, talentPool: 62 },
  { name: "Benin", continent: "Africa", fifaRank: 92, talentPool: 58 },
  {
    name: "Equatorial Guinea",
    continent: "Africa",
    fifaRank: 97,
    talentPool: 55,
  },
  { name: "Mozambique", continent: "Africa", fifaRank: 102, talentPool: 52 },
  { name: "Madagascar", continent: "Africa", fifaRank: 105, talentPool: 50 },
  { name: "Comoros", continent: "Africa", fifaRank: 108, talentPool: 55 },
  { name: "Niger", continent: "Africa", fifaRank: 109, talentPool: 48 },
  { name: "Libya", continent: "Africa", fifaRank: 111, talentPool: 52 },
  { name: "Tanzania", continent: "Africa", fifaRank: 112, talentPool: 50 },
  { name: "Kenya", continent: "Africa", fifaRank: 113, talentPool: 52 },
  { name: "Mauritania", continent: "Africa", fifaRank: 114, talentPool: 48 },
  { name: "The Gambia", continent: "Africa", fifaRank: 117, talentPool: 50 },
  { name: "Sudan", continent: "Africa", fifaRank: 118, talentPool: 48 },
  { name: "Namibia", continent: "Africa", fifaRank: 119, talentPool: 46 },
  { name: "Sierra Leone", continent: "Africa", fifaRank: 121, talentPool: 48 },
  { name: "Togo", continent: "Africa", fifaRank: 124, talentPool: 52 },
  { name: "Malawi", continent: "Africa", fifaRank: 126, talentPool: 45 },
  { name: "Zimbabwe", continent: "Africa", fifaRank: 129, talentPool: 48 },
  { name: "Rwanda", continent: "Africa", fifaRank: 131, talentPool: 45 },
  { name: "Guinea-Bissau", continent: "Africa", fifaRank: 133, talentPool: 42 },
  { name: "Congo", continent: "Africa", fifaRank: 134, talentPool: 50 },
  { name: "Botswana", continent: "Africa", fifaRank: 138, talentPool: 40 },
  {
    name: "Central African Republic",
    continent: "Africa",
    fifaRank: 139,
    talentPool: 38,
  },
  { name: "Liberia", continent: "Africa", fifaRank: 141, talentPool: 48 },
  { name: "Lesotho", continent: "Africa", fifaRank: 144, talentPool: 35 },
  { name: "Burundi", continent: "Africa", fifaRank: 145, talentPool: 42 },
  { name: "Ethiopia", continent: "Africa", fifaRank: 147, talentPool: 45 },
  { name: "Eswatini", continent: "Africa", fifaRank: 159, talentPool: 32 },
  { name: "South Sudan", continent: "Africa", fifaRank: 168, talentPool: 30 },
  { name: "Chad", continent: "Africa", fifaRank: 177, talentPool: 35 },
  { name: "Mauritius", continent: "Africa", fifaRank: 176, talentPool: 30 },
  {
    name: "São Tomé and Príncipe",
    continent: "Africa",
    fifaRank: 190,
    talentPool: 22,
  },
  { name: "Seychelles", continent: "Africa", fifaRank: 203, talentPool: 20 },
  { name: "Djibouti", continent: "Africa", fifaRank: 196, talentPool: 22 },
  { name: "Somalia", continent: "Africa", fifaRank: 200, talentPool: 25 },
  { name: "Eritrea", continent: "Africa", fifaRank: 211, talentPool: 18 },

  // ========== ÁSIA (AFC) ==========
  { name: "Japan", continent: "Asia", fifaRank: 18, talentPool: 83 },
  { name: "Iran", continent: "Asia", fifaRank: 20, talentPool: 78 },
  { name: "South Korea", continent: "Asia", fifaRank: 22, talentPool: 82 },
  { name: "Australia", continent: "Asia", fifaRank: 26, talentPool: 80 },
  { name: "Uzbekistan", continent: "Asia", fifaRank: 50, talentPool: 72 },
  { name: "Qatar", continent: "Asia", fifaRank: 51, talentPool: 72 },
  { name: "Iraq", continent: "Asia", fifaRank: 58, talentPool: 70 },
  { name: "Saudi Arabia", continent: "Asia", fifaRank: 60, talentPool: 76 },
  { name: "Jordan", continent: "Asia", fifaRank: 66, talentPool: 68 },
  { name: "UAE", continent: "Asia", fifaRank: 67, talentPool: 71 },
  { name: "Oman", continent: "Asia", fifaRank: 79, talentPool: 65 },
  { name: "Syria", continent: "Asia", fifaRank: 87, talentPool: 58 },
  { name: "Bahrain", continent: "Asia", fifaRank: 91, talentPool: 55 },
  { name: "China", continent: "Asia", fifaRank: 93, talentPool: 68 },
  { name: "Thailand", continent: "Asia", fifaRank: 95, talentPool: 60 },
  { name: "Palestine", continent: "Asia", fifaRank: 96, talentPool: 52 },
  { name: "Tajikistan", continent: "Asia", fifaRank: 101, talentPool: 50 },
  { name: "Kyrgyz Republic", continent: "Asia", fifaRank: 104, talentPool: 48 },
  { name: "Lebanon", continent: "Asia", fifaRank: 107, talentPool: 52 },
  { name: "Vietnam", continent: "Asia", fifaRank: 110, talentPool: 55 },
  { name: "Malaysia", continent: "Asia", fifaRank: 116, talentPool: 52 },
  { name: "Korea DPR", continent: "Asia", fifaRank: 120, talentPool: 55 },
  { name: "Indonesia", continent: "Asia", fifaRank: 122, talentPool: 55 },
  { name: "Kuwait", continent: "Asia", fifaRank: 135, talentPool: 48 },
  { name: "Philippines", continent: "Asia", fifaRank: 136, talentPool: 45 },
  { name: "Turkmenistan", continent: "Asia", fifaRank: 137, talentPool: 45 },
  { name: "India", continent: "Asia", fifaRank: 142, talentPool: 60 },
  { name: "Yemen", continent: "Asia", fifaRank: 148, talentPool: 38 },
  { name: "Singapore", continent: "Asia", fifaRank: 151, talentPool: 42 },
  { name: "Hong Kong", continent: "Asia", fifaRank: 153, talentPool: 40 },
  { name: "Taiwan", continent: "Asia", fifaRank: 174, talentPool: 32 },
  { name: "Myanmar", continent: "Asia", fifaRank: 163, talentPool: 38 },
  { name: "Afghanistan", continent: "Asia", fifaRank: 162, talentPool: 35 },
  { name: "Maldives", continent: "Asia", fifaRank: 173, talentPool: 28 },
  { name: "Cambodia", continent: "Asia", fifaRank: 179, talentPool: 32 },
  { name: "Bangladesh", continent: "Asia", fifaRank: 180, talentPool: 35 },
  { name: "Nepal", continent: "Asia", fifaRank: 182, talentPool: 32 },
  { name: "Mongolia", continent: "Asia", fifaRank: 185, talentPool: 28 },
  { name: "Laos", continent: "Asia", fifaRank: 187, talentPool: 25 },
  { name: "Brunei", continent: "Asia", fifaRank: 189, talentPool: 22 },
  { name: "Macau", continent: "Asia", fifaRank: 193, talentPool: 20 },
  { name: "Sri Lanka", continent: "Asia", fifaRank: 194, talentPool: 28 },
  { name: "Timor-Leste", continent: "Asia", fifaRank: 198, talentPool: 22 },
  { name: "Pakistan", continent: "Asia", fifaRank: 199, talentPool: 30 },
  { name: "Guam", continent: "Asia", fifaRank: 201, talentPool: 20 },
  { name: "Bhutan", continent: "Asia", fifaRank: 192, talentPool: 18 },

  // ========== OCEANIA (OFC) ==========
  { name: "New Zealand", continent: "Australia", fifaRank: 86, talentPool: 65 },
  {
    name: "New Caledonia",
    continent: "Australia",
    fifaRank: 149,
    talentPool: 45,
  },
  {
    name: "Solomon Islands",
    continent: "Australia",
    fifaRank: 152,
    talentPool: 40,
  },
  { name: "Fiji", continent: "Australia", fifaRank: 155, talentPool: 42 },
  { name: "Tahiti", continent: "Australia", fifaRank: 157, talentPool: 38 },
  { name: "Vanuatu", continent: "Australia", fifaRank: 160, talentPool: 35 },
  {
    name: "Papua New Guinea",
    continent: "Australia",
    fifaRank: 170,
    talentPool: 38,
  },
  { name: "Tonga", continent: "Australia", fifaRank: 197, talentPool: 22 },
  { name: "Samoa", continent: "Australia", fifaRank: 188, talentPool: 25 },
  {
    name: "Cook Islands",
    continent: "Australia",
    fifaRank: 186,
    talentPool: 20,
  },
  {
    name: "American Samoa",
    continent: "Australia",
    fifaRank: 184,
    talentPool: 18,
  },
];
