import type { TraitName } from "../types";

// Re-export names from the expanded names module
export { FIRST_NAMES, FIRST_NAMES_FEMALE, LAST_NAMES } from "./names";

export const PLAYER_TRAITS = {
  attacking: [
    {
      id: "finesse_shot",
      name: "Finesse Shot",
      rarity: "common",
      effect: "+5 Shooting Accuracy",
    },
    {
      id: "power_shot",
      name: "Power Shot",
      rarity: "common",
      effect: "+8 Shot Power",
    },
    {
      id: "chip_shot",
      name: "Chip Shot",
      rarity: "uncommon",
      effect: "+10 Finishing in 1v1",
    },
    {
      id: "flair",
      name: "Flair",
      rarity: "rare",
      effect: "+5 Dribbling, Unpredictable",
    },
    {
      id: "speed_dribbler",
      name: "Speed Dribbler",
      rarity: "uncommon",
      effect: "+8 Dribbling Speed",
    },
    {
      id: "technical_dribbler",
      name: "Technical Dribbler",
      rarity: "rare",
      effect: "+10 Close Control",
    },
    {
      id: "poacher",
      name: "Poacher",
      rarity: "uncommon",
      effect: "+15 Positioning in Box",
    },
    {
      id: "clinical_finisher",
      name: "Clinical Finisher",
      rarity: "rare",
      effect: "+12 Finishing",
    },
    {
      id: "target_man",
      name: "Target Man",
      rarity: "uncommon",
      effect: "+10 Heading, Hold-up Play",
    },
    {
      id: "fox_in_box",
      name: "Fox in the Box",
      rarity: "rare",
      effect: "+8 Reactions in Box",
    },
  ],

  playmaking: [
    {
      id: "playmaker",
      name: "Playmaker",
      rarity: "rare",
      effect: "+10 Vision, Passing",
    },
    {
      id: "long_passer",
      name: "Long Passer",
      rarity: "uncommon",
      effect: "+8 Long Passing",
    },
    {
      id: "through_ball",
      name: "Through Ball Specialist",
      rarity: "rare",
      effect: "+12 Through Balls",
    },
    {
      id: "set_piece_specialist",
      name: "Set Piece Specialist",
      rarity: "uncommon",
      effect: "+15 Free Kicks",
    },
    {
      id: "corner_specialist",
      name: "Corner Specialist",
      rarity: "common",
      effect: "+10 Corner Accuracy",
    },
    {
      id: "one_club_player",
      name: "One Club Player",
      rarity: "legendary",
      effect: "+5 All Stats at Home Club",
    },
  ],

  defensive: [
    {
      id: "tackle_master",
      name: "Tackle Master",
      rarity: "uncommon",
      effect: "+10 Tackling Success",
    },
    {
      id: "interception",
      name: "Interception Expert",
      rarity: "uncommon",
      effect: "+12 Interceptions",
    },
    {
      id: "aerial_defender",
      name: "Aerial Defender",
      rarity: "uncommon",
      effect: "+10 Heading Defense",
    },
    {
      id: "man_marker",
      name: "Man Marker",
      rarity: "rare",
      effect: "+8 Marking Tight",
    },
    {
      id: "sweeper",
      name: "Sweeper",
      rarity: "rare",
      effect: "+10 Positioning Coverage",
    },
    {
      id: "aggressive_defender",
      name: "Aggressive Defender",
      rarity: "common",
      effect: "+5 Aggression, -3 Discipline",
    },
  ],

  physical: [
    {
      id: "speedster",
      name: "Speedster",
      rarity: "uncommon",
      effect: "+12 Sprint Speed",
    },
    {
      id: "powerhouse",
      name: "Powerhouse",
      rarity: "uncommon",
      effect: "+10 Strength",
    },
    { id: "engine", name: "Engine", rarity: "rare", effect: "+15 Stamina" },
    {
      id: "injury_prone",
      name: "Injury Prone",
      rarity: "negative",
      effect: "-20% Injury Resistance",
    },
    {
      id: "resilient",
      name: "Resilient",
      rarity: "rare",
      effect: "+30% Injury Resistance",
    },
  ],

  mental: [
    { id: "leader", name: "Leader", rarity: "rare", effect: "+5 Team Morale" },
    {
      id: "captain",
      name: "Captain Material",
      rarity: "legendary",
      effect: "+10 Leadership, Team Boost",
    },
    {
      id: "big_game_player",
      name: "Big Game Player",
      rarity: "rare",
      effect: "+8 in Important Matches",
    },
    {
      id: "clutch",
      name: "Clutch",
      rarity: "legendary",
      effect: "+15 in Final Minutes",
    },
    {
      id: "mentality_monster",
      name: "Mentality Monster",
      rarity: "legendary",
      effect: "+10 under Pressure",
    },
    {
      id: "professional",
      name: "Professional",
      rarity: "uncommon",
      effect: "Slower Decline, +2 Training",
    },
    {
      id: "selfish",
      name: "Selfish",
      rarity: "negative",
      effect: "-5 Teamwork",
    },
    {
      id: "controversy",
      name: "Controversial",
      rarity: "negative",
      effect: "Higher Red Card Risk",
    },
  ],

  goalkeeper: [
    {
      id: "sweeper_keeper",
      name: "Sweeper Keeper",
      rarity: "uncommon",
      effect: "+10 Positioning Outside Box",
    },
    {
      id: "shot_stopper",
      name: "Shot Stopper",
      rarity: "rare",
      effect: "+12 Reflexes",
    },
    {
      id: "penalty_saver",
      name: "Penalty Saver",
      rarity: "rare",
      effect: "+20 Penalty Saves",
    },
    {
      id: "commanding",
      name: "Commanding Presence",
      rarity: "uncommon",
      effect: "+8 Aerial Dominance",
    },
    {
      id: "distribution",
      name: "Ball Distribution",
      rarity: "common",
      effect: "+10 Passing Accuracy",
    },
  ],
};

// Lucide icon names for traits
export const TRAIT_ICONS: { [key in TraitName]: string } = {
  // Attacking traits
  "Clinical Finisher": "Target",
  "Power Header": "ArrowUp",
  "Long Shots": "Rocket",
  Poacher: "Crosshair",
  "Target Man": "Radio",
  "Speed Merchant": "Zap",
  "Dribbling Wizard": "Wand2",
  "Flair Player": "Star",
  "Finesse Shot": "Wind",
  // Playmaking traits
  Playmaker: "Crown",
  "Set-piece Specialist": "Flag",
  Vision: "Eye",
  "Through Ball": "MoveRight",
  "Crossing Specialist": "ChevronsRight",
  // Midfield/work rate traits
  "Box to Box": "ArrowUpDown",
  "Deep Lying Playmaker": "Castle",
  Engine: "Cog",
  "Tireless Runner": "PersonStanding",
  "Ball Winner": "Hand",
  Interceptor: "ShieldHalf",
  // Defensive traits
  "Ball Playing Defender": "Shield",
  "No Nonsense Defender": "ShieldAlert",
  "Aerial Dominance": "ChevronsUp",
  "Last Man": "UserCheck",
  "Slide Tackle": "UserMinus",
  Marking: "Crosshair",
  // Goalkeeper traits
  "Sweeper Keeper": "Hand",
  "Shot Stopper": "Hand",
  "Penalty Saver": "Sparkles",
  "Command of Area": "Maximize",
  "Long Throw": "Circle",
  // Physical/mental traits
  Leadership: "Crown",
  Composure: "Brain",
  "Big Game Player": "Trophy",
  "Second Wind": "Wind",
  "Natural Fitness": "HeartPulse",
  "Injury Prone": "Stethoscope",
  // Utility traits
  Versatile: "Shapes",
  Discipline: "Handshake",
  "Two-Footed": "Footprints",
  "One-Club Man": "House",
  Consistency: "TrendingUp",
  // Footedness traits
  "Left-Footed Maestro": "Footprints",
  "Right-Footed Sniper": "Target",
  "Weak Foot": "Footprints",
  "Chip Shot": "CircleDot",
  "Outside Foot Shot": "CircleDot",
  "Power Shot": "Zap",
  "Long Shot Taker": "Target",
  "One-on-One Specialist": "User",
  "Acrobatic Finisher": "Sparkles",
  "Speed Dribbler": "Zap",
  "Technical Dribbler": "Wand2",
  Flair: "Star",
  Trickster: "Sparkles",
  "Ball Carrier": "Circle",
  "Long Passer": "MoveRight",
  "Pinpoint Crossing": "Target",
  "Tackles Back": "Shield",
  "Dives Into Tackles": "ArrowDown",
  Positioning: "MapPin",
  "Rushes Out Of Goal": "ArrowUp",
  "Comes For Crosses": "Hand",
  "Punches Fists": "Hand",
  "GK Long Throw": "MoveRight",
  "GK Flat Kick": "Circle",
  "One-on-One Rush": "ArrowUp",
  "Solid Player": "Shield",
  Strength: "Dumbbell",
  "Giant Throw-In": "MoveRight",
  "Aerial Threat": "ChevronsUp",
  "Power House": "Zap",
  "Team Player": "Users",
  "Argues With Officials": "MessageSquare",
  Driven: "Flame",
  "Early Adopter": "Lightbulb",
  Finesse: "Feather",
  "Play Simple": "Circle",
  "Avoids Using Weaker Foot": "Footprints",
  "Cautious With Crosses": "ShieldAlert",
  Selfish: "User",
  Inflexible: "Lock",
  "Injury Concern": "AlertTriangle",
  Teamwork: "Users",
};
