// Female first names - Greek and African
export const FIRST_NAMES_FEMALE_GREEK = [
    "Eleni", "Maria", "Sofia", "Anastasia", "Katerina", "Georgia", "Dimitra", "Athina", "Konstantina", "Stavroula",
    "Vasiliki", "Christina", "Despina", "Fotini", "Ioanna", "Panagiota", "Paraskevi", "Nikoleta", "Alexandra", "Theodora",
    "Agapi", "Aggeliki", "Aikaterini", "Aleka", "Aliki", "Amalia", "Androniki", "Angeliki", "Anna", "Antigoni",
    "Apostolia", "Areti", "Ariadni", "Artemis", "Aspasia", "Barbara", "Calliope", "Charitini", "Chrysanthi", "Chrysoula",
    "Dafni", "Danai", "Despoina", "Dionysia", "Dorothea", "Efrosini", "Efthymia", "Efterpi", "Efi", "Eftihia",
    "Eirini", "Eleftheria", "Elena", "Elisavet", "Ellisavet", "Elpiniki", "Elpida", "Emilia", "Ermioni", "Eudoxia",
    "Eugenia", "Evangelina", "Evanthia", "Evdokia", "Evi", "Evridiki", "Fani", "Filio", "Filippa", "Foteini",
    "Froso", "Glykeria", "Grammatiki", "Gregoria", "Helena", "Iliana", "Iris", "Irma", "Ismini", "Kalliopi",
    "Kalomira", "Kiki", "Kleopatra", "Konstantina", "Kyriaki", "Lamprini", "Loukia", "Lydia", "Mairi", "Marina",
    "Markella", "Martha", "Melina", "Melpo", "Melpomeni", "Myrto", "Nadia", "Natasa", "Nefeli", "Niki",
    "Olympia", "Ourania", "Pagona", "Panayiota", "Panayota", "Panagiota", "Parthena", "Penelope", "Peristera", "Polyxeni",
    "Rena", "Ritsa", "Roula", "Roxani", "Sappho", "Simela", "Smaragda", "Sophia", "Spyridoula", "Stella",
    "Styliani", "Sotiria", "Sousana", "Thaleia", "Thalia", "Theano", "Thekla", "Themis", "Theodora", "Theofania",
    "Theoni", "Thomai", "Toula", "Triantafyllia", "Varvara", "Vaso", "Vasileia", "Venetia", "Victoria", "Vivi",
    "Vivian", "Xanthippi", "Xenia", "Yanna", "Yianna", "Yvoni", "Zafeiria", "Zaharoula", "Zoi", "Zoitsa",
    "Adelaida", "Adriani", "Afroditi", "Agathi", "Agathoniki", "Aglaia", "Akrivi", "Aleka", "Alexia", "Alexis",
    "Amalia", "Amazona", "Amparo", "Anania", "Anastasia", "Andronikia", "Andromahi", "Anessia", "Angelina", "Anthoula",
    "Antonia", "Apostolina", "Aretina", "Argiro", "Argiro", "Argyro", "Ariadne", "Artemisa", "Aspro", "Athanasia",
    "Athena", "Augusta", "Avgerini", "Chrysoveloni", "Diamanto", "Diamanta", "Diamantina", "Doretta", "Domniki", "Dora",
    "Eftchia", "Efthalia", "Eftichia", "Eireen", "Eleftheria", "Eleonora", "Elessa", "Eliana", "Elianna", "Elissa",
    "Emmanouela", "Erasmia", "Erifyli", "Ermioni", "Ersi", "Esmeralda", "Eustathia", "Euthalia", "Evangeliki", "Evgenia",
    "Evmorfia", "Evridice", "Evrosyni", "Evthalia", "Evthimia", "Fanouraki", "Fara", "Fedra", "Filomena", "Filopatria",
    "Filothei", "Floria", "Fotoula", "Frantseska", "Frederika", "Galatea", "Garifallia", "Gelena", "Georgia", "Georgoula",
    "Gesthimani", "Gianna", "Giolanda", "Glafira", "Grammatina", "Hariclia", "Harmonia", "Hebe", "Hecuba", "Heliniki",
    "Hera", "Hermione", "Ileana", "Imelda", "Ioakimina", "Jordana", "Julia", "Kalliope", "Kleoniki", "Komnini",
    "Konstantia", "Koralia", "Kostandina", "Kostia", "Kyra", "Kiriaki", "Konstantinia", "Laoura", "Ligeria", "Loukiana",
    "Magdalini", "Malvina", "Margarita", "Marika", "Marigoula", "Mariza", "Maro", "Melahrini", "Melia", "Melissanthi",
    "Mersini", "Militsa", "Mirela", "Mirella", "Monika", "Nafsika", "Nassia", "Natassa", "Neofita", "Petroula",
    "Philomela", "Phira", "Photini", "Pinelopi", "Polychronia", "Polyna", "Potomia", "Prasina", "Praxiteli", "Prefti",
    "Prostasia", "Rena", "Reveka", "Rita", "Rodamni", "Rodanthi", "Rodopi", "Rodia", "Rosalia", "Rozalia"
];

export const FIRST_NAMES_FEMALE_AFRICAN = [
    "Asisat", "Chiamaka", "Rasheedat", "Francisca", "Ngozi", "Uchenna", "Ifeoma", "Chidinma", "Oluchi", "Adaeze",
    "Amina", "Fatou", "Awa", "Khady", "Mariama", "Seynabou", "Ndeye", "Binta", "Djeneba", "Kadiatou",
    "Fatoumata", "Aminata", "Aissatou", "Mariame", "Abeni", "Abimbola", "Adaeze", "Adanna", "Adaugo", "Adaure",
    "Adebola", "Adedoyin", "Adefunke", "Adeola", "Adewunmi", "Aisha", "Ajoke", "Akunna", "Amara", "Amina",
    "Abena", "Adanna", "Afua", "Akosuwa", "Akwele", "Amanishakheto", "Amara", "Ama", "Anike", "Araba",
    "Asantewaa", "Ayodele", "Blessing", "Bola", "Bunmi", "Chidera", "Chioma", "Divine", "Ebere", "Efua",
    "Ejiro", "Enitan", "Esohe", "Esther", "Ezinne", "Fanta", "Faridat", "Fatimata", "Favour", "Gambari",
    "Gift", "Glory", "Grace", "Hadiza", "Hassana", "Hauwa", "Hope", "Ifeanyi", "Ify", "Ihuoma",
    "Ije", "Imani", "Inem", "Inyang", "Isoken", "Jemila", "Jumoke", "Kadi", "Kadidia", "Kadijatu",
    "Kady", "Kemi", "Kezie", "Kofoworola", "Kofy", "Korkai", "Kudirat", "Ladi", "Latifat", "Lindiwe",
    "Madina", "Maimuna", "Makena", "Mame", "Marietou", "Mbali", "Miriam", "Modupe", "Muminat", "Nafissatou",
    "Naledi", "Nana", "Ndidi", "Nneka", "Nombini", "Nomusa", "Ntokozo", "Obiageli", "Ogechi", "Omolola",
    "Omolara", "Oni", "Onyinyechi", "Opelenge", "Oyin", "Peace", "Philile", "Precious", "Prudence", "Rabiatou",
    "Rachida", "Rashida", "Rebecca", "Rose", "Salamatu", "Sika", "Simisola", "Sisi", "Solange", "Soumba",
    "Sukai", "Temiloluwa", "Temitope", "Thabisa", "Thandeka", "Thandiwe", "Titilayo", "Titi", "Ubulwana", "Uchenna",
    "Uchechi", "Ugochi", "Uzoamaka", "Vimbai", "Wumi", "Yemisi", "Yewande", "Zanele", "Zara", "Zenabou",
    "Zina", "Zohra", "Abayomi", "Abike", "Abisola", "Abosede", "Adaeze", "Adamastor", "Adanna", "Adaobi",
    "Adaugo", "Adaura", "Adebanji", "Adebimpe", "Adebisi", "Adebowale", "Adejoke", "Adeleke", "Adeline", "Ademola",
    "Adenike", "Adenola", "Adeoluwa", "Adepeju", "Aderike", "Aderinsola", "Adesewa", "Adesina", "Adesola", "Adesumi",
    "Adewale", "Adey", "Adiatu", "Adjoa", "Aduke", "Adunni", "Adwoa", "Affiong", "Aghogho", "Ahadi",
    "Ajayi", "Aje", "Ajuonuma", "Akachi", "Akintola", "Akon", "Akosua", "Akua", "Alake", "Aminatou",
    "Amira", "Amokachi", "Anuli", "Aqissi", "Aremu", "Arike", "Ashetu", "Asiatu", "Ayinke", "Ayobami",
    "Ayomide", "Ayonkunle", "Ayoola", "Azizah", "Badewa", "Bamidele", "Banjoko", "Binta", "Bisola", "Bolarinwa",
    "Chidindu", "Chigozie", "Chika", "Chikoma", "Chinenye", "Chinwetel", "Chinwe", "Chisom", "Chukwu", "Damilare",
    "Daraja", "Dayo", "Diarra", "Djeneba", "Dolapo", "Dumebi", "Ekua", "Eloke", "Eniola", "Erelu",
    "Ese", "Etim", "Evbuomwa", "Fatiatou", "Fatsou", "Femi", "Folake", "Folami", "Folasade", "Folashade",
    "Fumilayo", "Funke", "Gimbiya", "Ginika", "Habiba", "Halima", "Hawwa", "Hawa", "Idia", "Ifunanya",
    "Ijele", "Ijeoma", "Iyabo", "Jamila", "Jokotade", "Kareema", "Karima", "Kewunje", "Khadijah", "Kubra",
    "Lamide", "Lateefat", "Mabel", "Madaraka", "Mairo", "Makeda", "Malika", "Maryama", "Masika", "Mauwa",
    "Mbafor", "Mbeke", "Mirembe", "Modinat", "Mojisola", "Moriyah", "Mosunmola", "Moyosore", "Munirat", "Nafisah"
];
