// Male first names - Greek and African
export const FIRST_NAMES_GREEK = [
    "Dimitrios", "Konstantinos", "Georgios", "Nikolaos", "Ioannis", "Christos", "Panagiotis", "Vasileios", "Athanasios", "Evangelos",
    "Spyridon", "Michail", "Andreas", "Alexandros", "Theodoros", "Stavros", "Petros", "Stefanos", "Ilias", "Antonios",
    "Anastasios", "Apostolos", "Aggelos", "Charalampos", "Dionysios", "Efstathios", "Emmanouil", "Filippos", "Fotios", "Gerasimos",
    "Grigorios", "Haralambos", "Iraklis", "Kostas", "Kyriakos", "Lazaros", "Leonidas", "Loukas", "Marios", "Matthaios",
    "Nektarios", "Nikitas", "Odysseas", "Pavlos", "Periklis", "Prokopios", "Savvas", "Sotirios", "Themistoklis", "Vasilis",
    "Achilleas", "Aimilios", "Aineias", "Akis", "Alexios", "Alkaios", "Alkiviadis", "Ambrosius", "Anastas", "Anax",
    "Andonios", "Anthimos", "Antipas", "Apollon", "Argyris", "Aristeidis", "Aristomenis", "Arsenios", "Artemios", "Asterios",
    "Athos", "Basilios", "Charilaos", "Christoforos", "Chrysanthos", "Chrysostomos", "Damaskinos", "Damianos", "Demetrios", "Dimitris",
    "Diogenis", "Drakon", "Efraim", "Eleftherios", "Epaminondas", "Epifanios", "Eraklis", "Eustathios", "Evagoras", "Evripidis",
    "Fanis", "Fivos", "Fotis", "Georgis", "Gerasim", "Gikas", "Giannis", "Gregoras", "Haralampos", "Hector",
    "Hektor", "Herakles", "Hermes", "Hieronymos", "Ignatios", "Iosif", "Irakleios", "Jason", "Kallistos", "Kalogeros",
    "Karpos", "Kassandros", "Kleanthis", "Kleonas", "Kleomenis", "Klimis", "Kolumbus", "Konstantis", "Kosmas", "Kriton",
    "Kyros", "Lampros", "Lefteris", "Leon", "Leontios", "Loizos", "Lysandros", "Makarios", "Makis", "Manolis",
    "Markos", "Meletios", "Menelaos", "Methodios", "Miltiadis", "Minos", "Mitsos", "Modestos", "Nearchos", "Nektaris",
    "Neoclis", "Nikos", "Orestis", "Orion", "Palladios", "Panayiotis", "Pantelis", "Paraskevas", "Paris", "Patroklos",
    "Pavlakis", "Pelasgos", "Perseas", "Philippos", "Phokion", "Platon", "Polydoros", "Polykarpos", "Polyvios", "Porfyrios",
    "Prodromos", "Prokopis", "Pyrros", "Rafail", "Romanos", "Sandros", "Serafeim", "Simos", "Simeon", "Sokrates",
    "Solon", "Sophoklis", "Sosos", "Sostrato", "Sotiras", "Spiros", "Stratos", "Symeon", "Tasos", "Telemachos",
    "Thalis", "Thanos", "Theodosios", "Theofilos", "Timotheos", "Titos", "Triantafyllos", "Tryfon", "Xenofon", "Yannis",
    "Yerasimos", "Zacharias", "Zenon", "Zisis", "Zotikos", "Adrastos", "Afxentios", "Agapios", "Agathangelos", "Agathos",
    "Agisilaos", "Aikaterinos", "Aineas", "Aischylos", "Akakios", "Alexandrakis", "Alexiou", "Alkeios", "Alkinoos", "Alkman",
    "Amfilochios", "Amyntas", "Anagnostis", "Ananiou", "Anargyros", "Anchises", "Androklis", "Andromahos", "Andronikos", "Angelis",
    "Antinous", "Antiochos", "Antipatros", "Apokaukos", "Apollodoros", "Apsaras", "Archimidis", "Areios", "Aristarchos", "Aristofanis",
    "Aristomachos", "Aristotelis", "Arkadios", "Artemas", "Asimakis", "Asopos", "Athanassiou", "Avgerinos", "Babis", "Bampis",
    "Bartholomaios", "Charalambou", "Charikleia", "Chaviaris", "Chromios", "Chrysos", "Daimachos", "Dalianis", "Dardanos", "Dareios",
    "Davlos", "Deligiannis", "Demitriou", "Demokritos", "Demosthenis", "Dimos", "Dionysus", "Dorieus", "Dorotheos", "Douglas",
    "Drosos", "Drysos", "Efraimidis", "Efstratios", "Efthymios", "Ekklisiastis", "Eleftheris", "Emmanos", "Emp", "Epafalos",
    "Epimenidis", "Erasmos", "Erastos", "Erechtheas", "Ergatikos", "Erifili", "Erotokritos", "Eudokimos", "Eugenios", "Eulalios",
    "Eumenios", "Euphrates", "Eupolis", "Euripidis", "Eurycles", "Eurymedon", "Eusebios", "Euthymios", "Evanthios", "Evgenidis",
    "Evgenis", "Evlamios", "Evmenis", "Evripidou", "Exarchos", "Faidon", "Fanourios", "Farmakis", "Feidias", "Findaros"
];

export const FIRST_NAMES_AFRICAN = [
    "Abdul", "Adama", "Amadou", "Cheick", "Ibrahim", "Ismael", "Karim", "Mohamed", "Moussa", "Oumar",
    "Sadio", "Sekou", "Souleymane", "Yaya", "Zakaria", "Zoumana", "Bakary", "Boubacar", "Drissa", "Fode",
    "Habib", "Idrissa", "Kalidou", "Lamine", "Mamadou", "Naby", "Ousmane", "Pape", "Salif", "Tidiane",
    "Aboubacar", "Achiou", "Adebayor", "Afolabi", "Ahmed", "Aiyegbeni", "Ajayi", "Akpom", "Ali", "Alioune",
    "Alinane", "Aliou", "Alpha", "Amidou", "Amine", "Amougou", "Amos", "Anicet", "Aristide", "Arouna",
    "Aurelien", "Ayah", "Babacar", "Bachirou", "Badara", "Badou", "Badreddine", "Bakambu", "Bakari", "Balotelli",
    "Bangaly", "Bangoura", "Bassala", "Bassam", "Baye", "Bazou", "Belaid", "Benali", "Benjamin", "Benoit",
    "Binouel", "Birima", "Bissouma", "Bobo", "Boli", "Bonfils", "Bouba", "Boubakar", "Boulaye", "Bruno",
    "Calvin", "Cedric", "Cheikh", "Chigozie", "Chinedu", "Christian", "Christopher", "Cisse", "Claude", "Clement",
    "Clinton", "Collins", "Cyril", "Daouda", "David", "Demba", "Denis", "Desire", "Dieumerci", "Diomande",
    "Djakaridja", "Djibril", "Djibrilou", "Djiby", "Djiguiba", "Dominique", "Doudou", "Dramane", "Edouard", "Elhadji",
    "Elie", "Elijah", "Emmanuel", "Eric", "Etienne", "Fabrice", "Famara", "Feghouli", "Felix", "Ferdinand",
    "Fernand", "Florent", "Fodie", "Franck", "Frederic", "Gaetan", "Gaoussou", "Gassama", "Gedeon", "Gerard",
    "Gernot", "Ghislain", "Gideon", "Gilbert", "Gnegneri", "Godfred", "Godwin", "Goneri", "Guy", "Hamani",
    "Hamidou", "Haruna", "Henri", "Herve", "Hilaire", "Hippolyte", "Ibrahima", "Ibrahimovic", "Ideye", "Ighalo",
    "Ikechukwu", "Issa", "Jacques", "Jean", "Joel", "John", "Jonathan", "Joseph", "Jules", "Junior",
    "Kabore", "Kadidiatou", "Kalifa", "Kamso", "Kassim", "Kayode", "Kelechi", "Kenneth", "Kevin", "Khalifou",
    "Koffi", "Koita", "Koloniama", "Komlan", "Kone", "Kouakou", "Kouame", "Kouyate", "Lacina", "Landry",
    "Laurent", "Lazare", "Leon", "Leo", "Leopold", "Louis", "Loua", "Loum", "Lucas", "Lucien",
    "Ludovic", "Mabrouk", "Madiambal", "Mady", "Makan", "Makha", "Makouta", "Malang", "Mali", "Mame",
    "Mamouda", "Mansour", "Mapathe", "Marc", "Marcel", "Marcellin", "Marcus", "Martial", "Martin", "Massamba",
    "Mathieu", "Matteo", "Maurice", "Mbaye", "Meddie", "Medi", "Modou", "Mohamed", "Mohammed", "Moktar",
    "Morlaye", "Mouhamed", "Mouhameth", "Mourad", "Moussa", "Moustafa", "Moustapha", "Mukoko", "Musa", "Mzwandile",
    "Nampalys", "Ndoye", "Nduka", "Nicholas", "Nil", "Nicolas", "Nnamdi", "Noah", "Noel", "Nouha",
    "Nsame", "Obafemi", "Obiora", "Odion", "Oghenekaro", "Oladapo", "Olaleye", "Olawale", "Olivier", "Olusola",
    "Omenuke", "Onuachu", "Oscar", "Osei", "Oubaida", "Ousseynou", "Papa", "Pascal", "Patrice", "Patrick",
    "Paul", "Peter", "Philippe", "Phillippe", "Pierre", "Prospere", "Rabehi", "Rachid", "Rafik", "Raouf",
    "Raymond", "Razak", "Regis", "Remi", "Riad", "Richard", "Richmond", "Robert", "Roger", "Roland",
    "Romain", "Romaric", "Rubin", "Rudy", "Sacha", "Sadrak", "Said", "Saidou", "Salaheddine", "Samuel",
    "Sana", "Sane", "Sanna", "Saphir", "Sarr", "Seko", "Serge", "Seth", "Seydou", "Simon"
];
