// Last names - Argentinian/Dutch/Turkish/Japanese
export const LAST_NAMES_ARGENTINIAN = [
    "Gonzalez", "Rodriguez", "Garcia", "Fernandez", "Lopez", "Martinez", "Perez", "Gomez", "Sanchez", "Romero",
    "Diaz", "Torres", "Alvarez", "Ruiz", "Morales", "Jimenez", "Ramirez", "Castro", "Ortiz", "Mendoza",
    "Silva", "Rojas", "Herrera", "Medina", "Gutierrez", "Aguilar", "Vargas", "Navarro", "Ramos", "Sosa",
    "Moreno", "Flores", "Acosta", "Benitez", "Molina", "Cabrera", "Luna", "Pereyra", "Lucero", "Aguirre",
    "Rios", "Arias", "Figueroa", "Miranda", "Cardozo", "Ledesma", "Villalba", "Caceres", "Castillo", "Vera",
    "Duarte", "Rivero", "Ibarra", "Santos", "Velazquez", "Ramirez", "Godoy", "Soria", "Campos", "Rey",
    "Blanco", "Gimenez", "Dominguez", "Cano", "Vega", "Franco", "Quiroga", "Rosales", "Barreto", "Paez",
    "Escobar", "Villanueva", "Valdez", "Moyano", "Paz", "Ponce", "Maidana", "Contreras", "Garay", "Coronel",
    "Gallardo", "Leiva", "Nuñez", "Alarcon", "Peralta", "Caballero", "Zarate", "Vidal", "Bravo", "Cordoba",
    "Ortega", "Leguizamon", "Ojeda", "Mendez", "Bernal", "Carrizo", "Paredes", "Avila", "Barrios", "Suarez",
    "Avalos", "Messi", "Maradona", "Batistuta", "Zanetti", "Simeone", "Redondo", "Riquelme", "Tevez", "Aguero",
    "Mascherano", "Di Maria", "Lavezzi", "Higuain", "Zabaleta", "Gaitan", "Pastore", "Lamela", "Musa", "Fazio",
    "Otamendi", "Mercado", "Rojo", "Tagliafico", "Acuña", "Paredes", "Lo Celso", "De Paul", "Lautaro", "Dybala",
    "Correa", "Ocampos", "Montiel", "Romero", "Martinez", "Enzo", "Mac Allister", "Julian", "Garnacho", "Pezzella",
    "Demichelis", "Heinze", "Sorino", "Cambiasso", "Milito", "Pallermo", "Crespo", "Veron", "Samuel", "Ayala",
    "Gonzalo", "Aimar", "Saviola", "Ortega", "Gallardo", "Almeyda", "Chamot", "Sensini", "Batista", "Burruchaga",
    "Valdano", "Caniggia", "Ctella", "Diaz", "Fillol", "Kempes", "Passarella", "Tarantini", "Ardiles", "Villa",
    "Houseman", "Luque", "Bertoni", "Gallego", "Olarticoechea", "Enrique", "Gareca", "Islas", "Giusti", "Pumpido",
    "Ruggeri", "Basile", "Fabbri", "Dezotti", "Troglio", "Sensini", "Monzon", "Simon", "Claudio", "Esnaider",
    "Balbo", "Bassedas", "Berti", "Burrito", "Canale", "Chapui", "Chilavert", "Cirigliano", "Cuper", "Delgado",
    "Ahumada", "Allende", "Altamirano", "Amato", "Andreotti", "Aparicio", "Aramburu", "Arganaraz", "Arrieta", "Artero",
    "Asencio", "Avendano", "Bacigalupo", "Balbuena", "Balderas", "Balmaceda", "Banega", "Barrera", "Barros", "Basaure",
    "Batalla", "Belfiore", "Beltran", "Betancourt", "Bogado", "Bonafini", "Bordagaray", "Borjas", "Bracamonte", "Brunetta",
    "Bulacio", "Bustamante", "Cabral", "Calamaro", "Calderón", "Calvino", "Camacho", "Cangiano", "Cantero", "Capdevila",
    "Capria", "Cardoso", "Carnevale", "Carranza", "Carrasco", "Carrera", "Casares", "Casariego", "Cazzaniga", "Ceballo",
    "Centeno", "Cerda", "Cerquetella", "Cetraro", "Chamorro", "Ciancia", "Cicchetti", "Cisneros", "Colautti", "Collado",
    "Colombres", "Cosentino", "Cozzolino", "Cravero", "Crespo", "Croce", "Cruciani", "Cuello", "D'Alessandro", "D'Andrea",
    "D'Elía", "D'Onofrio", "Dalessandro", "Damiani", "De la Fuente", "De Rosa", "Del Potro", "Del Valle", "Delgadillo", "Dellacasa",
    "Di Benedetto", "Di Caprio", "Di Lorenzo", "Di Martino", "Di Paolo", "Domíguez", "Donadío", "Drago", "Echagüe", "Echeverría",
    "Elizalde", "Episcopo", "Errecalde", "Escalada", "Escudero", "Espíndola", "Espinola", "Esteban", "Etcharren", "Etcheberry"
];

export const LAST_NAMES_DUTCH = [
    "De Jong", "Jansen", "De Vries", "Van den Berg", "Van Dijk", "Bakker", "Visser", "Smit", "Meijer", "De Boer",
    "Mulder", "De Groot", "Bos", "Vos", "Peters", "Hendriks", "Van Leeuwen", "Dekker", "Brouwer", "De Wit",
    "Dijkstra", "Smits", "De Graaf", "Van der Meer", "Van der Linden", "Kok", "Jacobs", "De Haan", "Vermeer", "Van den Heuvel",
    "Schouten", "Van Beek", "Willems", "Van Vliet", "Van de Ven", "Hoekstra", "Maas", "Verhoeven", "Koster", "Van Dam",
    "Hermans", "Van der Heijden", "Scholten", "Postma", "Kuipers", "Van Schaik", "Veenstra", "Van Loon", "Koopman", "De Vos",
    "Van der Velden", "Van der Wal", "Koning", "Van Wijk", "Bosman", "Groen", "Evers", "Van Es", "Gerritsen", "Akkerman",
    "Van der Zwan", "Huisman", "Van Eck", "Molenaar", "De Wolf", "Bosch", "Sanders", "Van der Werf", "Wolters", "De Ridder",
    "Ruiter", "Peeters", "Kuijpers", "Van der Bij", "Van der Horst", "Berendsen", "Vonk", "Van Rijn", "De Ruiter", "Van der Molen",
    "Blom", "Van den Brink", "Stok", "Van der Steen", "Cruyff", "Van Basten", "Gullit", "Rijkaard", "Koeman", "Bergkamp",
    "Kluivert", "Davids", "Sneijder", "Van Persie", "Robben", "Van Nistelrooy", "Seedorf", "Van der Vaart", "Kuyt", "Van Bronckhorst",
    "De Boer", "Stam", "Van der Sar", "Reiziger", "Bosvelt", "De Goey", "Overmars", "Jonk", "Taument", "Winter",
    "Van Gaal", "Advocaat", "Koeman", "Ten Hag", "Blind", "Van Bommel", "Van Marwijk", "Hiddink", "Michels", "Happel",
    "Litmanen", "Suurbier", "Haan", "Krol", "Neeskens", "Rep", "Rensenbrink", "Kaiser", "Hanegem", "Jansen",
    "Van der Kuijlen", "Petrovic", "Helder", "Troost", "Loderus", "Van Tiggelen", "Vanenburg", "Van Gastel", "Boere", "Witschge",
    "Aalbers", "Aarts", "Adriaans", "Adriaansen", "Aertsen", "Akker", "Alblas", "Alderliesten", "Ammerlaan", "Andriessen",
    "Ansems", "Arends", "Arntz", "Arts", "Baaij", "Baas", "Balvers", "Beek", "Beelen", "Beijer",
    "Bekkers", "Beltman", "Berends", "Berg", "Bergen", "Bergman", "Berkhout", "Berkman", "Berman", "Berning",
    "Bervoets", "Bessems", "Beumer", "Bijl", "Bijlsma", "Binkhorst", "Blaauw", "Blanken", "Blankert", "Bleeker",
    "Boekema", "Boekman", "Boer", "Boersma", "Boeters", "Bolhaar", "Boom", "Boon", "Boone", "Boonstra",
    "Boot", "Borger", "Borgman", "Borsboom", "Borsje", "Bosma", "Botman", "Botter", "Boudestein", "Bouwens",
    "Bouwman", "Brand", "Brands", "Branger", "Braspenning", "Bredewold", "Breeman", "Breugem", "Brink", "Brinkman",
    "Broek", "Broeks", "Broekmans", "Brouwer", "Bruggeman", "Bruijn", "Bruining", "Bruls", "Bruning", "Brussee",
    "Bugter", "Buijs", "Buikema", "Buitenhuis", "Buitink", "Bulder", "Bults", "Bunink", "Bunk", "Burg",
    "Burggraaf", "Burgman", "Busch", "Busker", "Busman", "Butter", "Cornelissen", "Corsten", "Crijns", "Cuijpers",
    "Daams", "Daal", "Daalman", "Dabbinga", "Dalen", "Dalhuisen", "Dam", "Damman", "Damoiseaux", "Dekkers",
    "Demmers", "Den Hartog", "Den Ouden", "Derks", "Dessing", "Deurloo", "DeVos", "Dicker", "Didden", "Diederik",
    "Dieleman", "Dierckx", "Dietz", "Dijkers", "Dijkgraaf", "Dijkman", "Dikkers", "Dollevoet", "Dolman", "Donders",
    "Donker", "Donkersloot", "Dool", "Doorn", "Doornbos", "Doornekamp", "Doornik", "Dop", "Douma", "Drenth",
    "Driessen", "Drost", "Druten", "Duin", "Duindam", "Duine", "Duiverman", "Duk", "Dullemen", "Dupont",
    "Duran", "Duyzer", "Ebben", "Eck", "Eeken", "Egas", "Egberts", "Eggen", "Eijk", "Eikelboom"
];

export const LAST_NAMES_TURKISH = [
    "Yilmaz", "Kaya", "Demir", "Celik", "Sahin", "Yildirim", "Yildiz", "Ozturk", "Aydin", "Ozdemir",
    "Arslan", "Dogan", "Kilic", "Aslan", "Cetin", "Kara", "Koc", "Kurt", "Ozkan", "Simsek",
    "Erdogan", "Polat", "Coskun", "Korkmaz", "Gunes", "Cinar", "Aksoy", "Tekin", "Koç", "Tas",
    "Keskin", "Kaplan", "Acar", "Bilgin", "Bulut", "Unal", "Altun", "Bayrak", "Dursun", "Ertugrul",
    "Gul", "Karaca", "Sen", "Turk", "Yavuz", "Akgun", "Ay", "Erdem", "Kartal", "Ozer",
    "Ozen", "Sezer", "Soylu", "Turan", "Aktas", "Bayram", "Boz", "Can", "Erol", "Guler",
    "Saglam", "Tan", "Yuce", "Akin", "Aktasn", "Bal", "Caliskan", "Cakmak", "Dag", "Durmaz",
    "Ekinci", "Gunay", "Ince", "Isik", "Kahraman", "Karakaya", "Karatas", "Keser", "Kiral", "Kocer",
    "Kulak", "Oguz", "Orhan", "Ozcelik", "Ozcan", "Ozkaya", "Ozmen", "Pala", "Sonmez", "Soysal",
    "Tamer", "Topal", "Toprak", "Tosun", "Tunc", "Tuncer", "Ucar", "Ugur", "Ustun", "Yarar",
    "Yazici", "Yuksel", "Ates", "Ozgur", "Akyuz", "Basaran", "Bayraktar", "Bilen", "Bozkurt", "Cicek",
    "Deniz", "Demirel", "Dincer", "Ekici", "Ertan", "Gokce", "Gumush", "Guney", "Hacioglu", "Ilhan",
    "Karabas", "Karadag", "Karakus", "Kavak", "Kemalettin", "Kilinc", "Koca", "Kucukyilmaz", "Mert", "Nacar",
    "Ozgul", "Ozkok", "Ozpinar", "Savran", "Sertkaya", "Sever", "Tanriverdi", "Tekeli", "Teoman", "Tok",
    "Topcu", "Yalcin", "Yanik", "Akbas", "Akca", "Akdeniz", "Akmese", "Alkan", "Altinel", "Altintas",
    "Altunay", "Altunbas", "Altuntas", "Anbarci", "Arabaci", "Arabul", "Aras", "Argun", "Arikan", "Asan",
    "Asik", "Atalay", "Atasoy", "Atilgan", "Avci", "Ayaz", "Aydemir", "Aydogan", "Aygun", "Ayhan",
    "Aykut", "Aymalp", "Ayranci", "Azak", "Babacan", "Babayigit", "Bagci", "Bakir", "Balta", "Barut",
    "Basak", "Baser", "Basmaci", "Batuk", "Bebek", "Bedir", "Bektas", "Benli", "Berkay", "Berker",
    "Berk", "Besoglu", "Bican", "Bilal", "Bilgic", "Boduroglu", "Bokesoy", "Bolat", "Boran", "Bostanci",
    "Boyraz", "Budak", "Bulanik", "Burak", "Cabuk", "Caglar", "Cakan", "Callskan", "Canik", "Cankurt",
    "Capar", "Capkin", "Cebi", "Celep", "Celikkol", "Cengiz", "Cetiner", "Ceyhan", "Ceylan", "Cifci",
    "Coban", "Cubuk", "Cubukcu", "Cuhadar", "Dagli", "Dane", "Deger", "Delibas", "Demirag", "Demiralp",
    "Demirci", "Deveci", "Dikmen", "Dinler", "Dizdar", "Doganer", "Dogru", "Dolunay", "Dombayci", "Doner",
    "Duman", "Duran", "Durmus", "Duyar", "Ebrar", "Elci", "Erbakan", "Ercan", "Erden", "Erdil",
    "Erdogmus", "Ergin", "Ergul", "Ergün", "Erkoc", "Erkul", "Erman", "Ersoz", "Ertunc", "Eser",
    "Eskici", "Eyice", "Fidan", "Filiz", "Genç", "Gencer", "Gergin", "Gokberk", "Gokcen", "Gokhan",
    "Gokmen", "Goksu", "Gokturk", "Gokyigit", "Gonul", "Gorur", "Gucer", "Guder", "Gulum", "Gultekin",
    "Gumustash", "Gunal", "Gunalp", "Gunar", "Gunduz", "Gungor", "Gurcan", "Gurdag", "Gurer", "Gurol",
    "Halici", "Hamarat", "Hasanoglu", "Hemdem", "Hizal", "Hosgor", "Huseyin", "Icel", "Igci", "Ipek"
];

export const LAST_NAMES_JAPANESE = [
    "Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Kato",
    "Yoshida", "Yamada", "Sasaki", "Yamaguchi", "Saito", "Matsumoto", "Inoue", "Kimura", "Hayashi", "Shimizu",
    "Yamazaki", "Mori", "Abe", "Ikeda", "Hashimoto", "Yamashita", "Ishikawa", "Nakajima", "Maeda", "Fujita",
    "Ogawa", "Goto", "Okada", "Hasegawa", "Murakami", "Kondo", "Ishii", "Saito", "Sakamoto", "Endo",
    "Aoki", "Fujii", "Nishimura", "Fukuda", "Ota", "Miura", "Fujiwara", "Okamoto", "Matsuda", "Nakagawa",
    "Nakano", "Harada", "Ono", "Tamura", "Takeuchi", "Kaneko", "Wada", "Nakayama", "Ishida", "Ueda",
    "Morita", "Hara", "Shibata", "Sakai", "Kudo", "Yokoyama", "Miyazaki", "Miyamoto", "Uchida", "Takagi",
    "Ando", "Taniguchi", "Otsuka", "Chiba", "Kubo", "Matsui", "Iwasaki", "Sakurai", "Kinoshita", "Noguchi",
    "Matsuo", "Nomura", "Kikuchi", "Sano", "Onishi", "Sugiyama", "Arai", "Kawamura", "Honda", "Hirano",
    "Fujimoto", "Kawasaki", "Koyama", "Takada", "Morimoto", "Tsuchiya", "Sugawara", "Hidaka", "Imai", "Masuda",
    "Nagai", "Ishihara", "Ozawa", "Hamada", "Yamanaka", "Higuchi", "Yano", "Ozaki", "Iwata", "Nakatsuka",
    "Fukushima", "Kitamura", "Kagawa", "Hattori", "Kurosawa", "Hirata", "Ueno", "Takeda", "Komatsu", "Hirai",
    "Kawaguchi", "Maruyama", "Sakata", "Mitsui", "Honda", "Kawai", "Hagiwara", "Miyake", "Mochizuki", "Asano",
    "Nakata", "Okazaki", "Yoshikawa", "Nagata", "Hamasaki", "Tsuji", "Noda", "Furukawa", "Nakanishi", "Matsushita",
    "Akiyama", "Baba", "Eguchi", "Fujioka", "Funakoshi", "Furuta", "Hamamoto", "Hara", "Harada", "Hayakawa",
    "Hayata", "Higa", "Hirose", "Hoshino", "Ichikawa", "Igarashi", "Imamura", "Inaba", "Inamoto", "Inui",
    "Ishiguro", "Isobe", "Iwamoto", "Izumi", "Kamiya", "Kanda", "Kanemaru", "Katagiri", "Katayama", "Kawabata",
    "Kawano", "Kawakami", "Kido", "Kikuchi", "Kishi", "Kitahara", "Kitao", "Koga", "Koike", "Konno",
    "Kurata", "Kurita", "Kuroda", "Kuwabara", "Machida", "Maekawa", "Makino", "Maruta", "Mashimo", "Masui",
    "Matsubara", "Matsuura", "Minami", "Miyashita", "Mizuno", "Mizutani", "Mochida", "Morioka", "Mukai", "Muramatsu",
    "Murase", "Naka", "Nakahara", "Nakao", "Nakazawa", "Nishida", "Nishikawa", "Nishioka", "Nitta", "Noda",
    "Nomoto", "Obata", "Oda", "Ogasawara", "Ogata", "Ogino", "Ogura", "Ohashi", "Ohta", "Ohtsuka",
    "Oikawa", "Oishi", "Okabe", "Okajima", "Okamura", "Okano", "Okita", "Okuno", "Omori", "Onodera",
    "Osaki", "Oshima", "Otani", "Otsu", "Oyama", "Saeki", "Sagawa", "Sakaguchi", "Sakashita", "Sakata",
    "Samejima", "Sawada", "Segawa", "Sekiguchi", "Sekine", "Seta", "Shibayama", "Shigematsu", "Shimada", "Shimomura",
    "Shinozaki", "Shirai", "Shiratori", "Shoji", "Sonoda", "Suda", "Sugiura", "Sugita", "Sumida", "Sunaga",
    "Tabata", "Tachibana", "Taguchi", "Tahara", "Tajima", "Takami", "Takano", "Takashima", "Tamaki", "Tanemura",
    "Tanino", "Terada", "Teramoto", "Toda", "Tokuda", "Tonami", "Torii", "Tsubouchi", "Tsuji", "Tsumura",
    "Tsuno", "Tsunoda", "Uesugi", "Ueyama", "Uno", "Usui", "Uwai", "Watabiki", "Yagi", "Yamabe",
    "Yamane", "Yamashiro", "Yamauchi", "Yasuda", "Yasui", "Yokota", "Yoshino", "Yoshioka", "Yuki", "Yuasa"
];
