// Last names - Korean/Arabic/Scandinavian/Eastern European
export const LAST_NAMES_KOREAN = [
    "Kim", "Lee", "Park", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim",
    "Han", "Oh", "Seo", "Shin", "Kwon", "Hwang", "Ahn", "Song", "Hong", "Baek",
    "Nam", "Moon", "Yang", "Ko", "Bae", "Jo", "Ha", "Yu", "Jeon", "Yun",
    "Yoo", "Ryu", "Kwak", "Son", "Sung", "Sim", "Won", "Jin", "Chun", "Noh",
    "Jeong", "Chang", "Byun", "Woo", "Goo", "Min", "Go", "Suh", "Sohn", "Chung",
    "Ma", "Gu", "Ji", "Pyo", "Eom", "Cha", "Dong", "Ban", "In", "Gi",
    "Heo", "Sa", "Pi", "Tae", "Chi", "Ku", "Geum", "Ro", "Pang", "Sul",
    "Bong", "Ho", "Yum", "So", "Paek", "Yeo", "Gal", "Tak", "Ran", "Sa",
    "Seol", "Ja", "Tu", "Si", "Bo", "Chu", "Oh", "Gwak", "Ye", "Sun",
    "Rim", "Do", "No", "Keum", "Gam", "Pae", "Wang", "Kong", "Mo", "Pan",
    "Hyun", "Shim", "Ok", "Seong", "Cho", "Choe", "Gang", "An", "Song", "Jeong",
    "Bak", "Yun", "Jang", "Lim", "Na", "Mun", "Yi", "Roh", "Jo", "Cheon",
    "So", "Hwang", "Huh", "Ki", "Kwak", "Ma", "Sim", "Suh", "Uh", "Wi",
    "Won", "Woon", "Yim", "Baik", "Jin", "Jong", "Seung", "Gun", "Myung", "Nam",
    "Sangho", "Wook", "Young", "Byeong", "Beom", "Dong", "Hyuk", "Cheol", "Choon", "Dae",
    "Gil", "Gyeong", "Hak", "Hwan", "Hyeong", "Il", "In", "Jae", "Joong", "Kyung",
    "Mahn", "Moo", "Pil", "Pyung", "Sang", "Sik", "Soo", "Sung", "Sun", "Tae",
    "Won", "Woo", "Yong", "Yul", "Hae", "Han", "Ho", "Hwang", "Hyeon", "Joon",
    "Chang", "Geon", "Gong", "Gyeom", "Huyn", "Heon", "Seok", "Seon", "Sik", "Sup",
    "Yeol", "Yun", "Baek", "Bok", "Bu", "Chae", "Cho", "Choi", "Eun", "Geum",
    "Gu", "Guk", "Gwang", "Gwon", "Go", "Gong", "Haam", "Hahm", "Hahng", "Hang",
    "Heo", "Hi", "Him", "Hin", "Huh", "Hyeob", "Hyup", "Jang", "Jangmi", "Jeon",
    "Jeoung", "Jew", "Jhiu", "Jin", "Jo", "Joh", "Joun", "Jun", "Ka", "Keo",
    "Kil", "Kim", "Kong", "Koo", "Kuh", "Kun", "Kur", "Kye", "Kyeon", "Kyung",
    "Lee", "Maeng", "Mah", "Mahn", "Mang", "Mi", "Min", "Minn", "Mo", "Moc",
    "Mok", "Moo", "Moon", "Mun", "Myeong", "Myung", "Na", "Naem", "Nahm", "Nam",
    "Nho", "Nim", "O", "Oak", "Ock", "Oh", "Ok", "Ong", "Ooh", "Paik",
    "Pan", "Pang", "Park", "Phyo", "Pi", "Pil", "Ping", "Po", "Pyo", "Pyong",
    "Ra", "Ran", "Rang", "Rhee", "Ri", "Rim", "Rin", "Ri", "Ro", "Roh",
    "Roo", "Ryoo", "Sa", "Sang", "Se", "Seo", "Seol", "Seom", "Seong", "Shi"
];

export const LAST_NAMES_ARABIC = [
    "Al-Rashid", "Al-Hamad", "Al-Zahrani", "Al-Otaibi", "Al-Ghamdi", "Al-Harbi", "Al-Shammari", "Al-Mutairi", "Al-Qahtani", "Al-Salem",
    "Al-Dosari", "Al-Omari", "Al-Mahdi", "Al-Mansour", "Al-Subaie", "Al-Hajri", "Hassan", "Hussein", "Abbas", "Mansour",
    "Khalil", "Ibrahim", "Mahmoud", "Said", "Ahmed", "Ali", "Mohammed", "Youssef", "Omar", "Abdallah",
    "Nasser", "Salem", "Khalid", "Fahad", "Saeed", "Rashid", "Sultan", "Hamad", "Abdullah", "Saleh",
    "Faisal", "Turki", "Bandar", "Nawaf", "Thamer", "Majed", "Meshal", "Waleed", "Badr", "Mishari",
    "Abdulaziz", "Abdulrahman", "Saud", "Nayef", "Mazen", "Osama", "Tariq", "Jamal", "Karim", "Zaid",
    "Talal", "Muhannad", "Amer", "Hisham", "Fawaz", "Adel", "Ihsan", "Wael", "Rami", "Bilal",
    "Bassam", "Hazim", "Nabil", "Riad", "Samir", "Younis", "Ghassan", "Marwan", "Hatem", "Nasr",
    "Ben Ali", "Ben Ahmed", "Ben Mohamed", "Ben Youssef", "Ben Salah", "Ben Khaled", "Ben Hassan", "Ben Hussein", "Ben Mahmoud", "Ben Omar",
    "Bouazizi", "Bouzid", "Brahimi", "Belhaj", "Belaid", "Bensalem", "Benamor", "Bendjebbar", "Benali", "Benaissa",
    "Cherif", "Chergui", "Chaabane", "Chadli", "Chebbi", "Chakir", "Chafik", "Chaker", "Chalabi", "Chamsi",
    "Dahbi", "Djebali", "Dougui", "Dridi", "Djalil", "Djemaa", "Djaballah", "Djelassi", "Djelloul", "Djoudi",
    "El-Amin", "El-Arabi", "El-Ghali", "El-Hadi", "El-Hasni", "El-Khatib", "El-Mansouri", "El-Masri", "El-Moussa", "El-Naggar",
    "El-Sayed", "El-Shafei", "El-Zein", "Fares", "Farid", "Fattah", "Fawzi", "Fridja", "Fouad", "Ghani",
    "Ghazali", "Ghediri", "Guerrab", "Guermazi", "Gueye", "Habib", "Hachemi", "Hafedh", "Hafsaoui", "Hajjam",
    "Hamdi", "Hammoudi", "Hamza", "Hanafi", "Haroun", "Heddi", "Hicham", "Houari", "Houichi", "Houssam",
    "Idrissi", "Jabri", "Jaber", "Jadid", "Jalloul", "Jarmouni", "Jebali", "Jellouli", "Kaabi", "Kadri",
    "Kamali", "Karray", "Kassab", "Kechiche", "Keddar", "Khadir", "Khaldi", "Khalli", "Khamis", "Khattab",
    "Khodja", "Labidi", "Lacheb", "Lakhdar", "Lamari", "Larbi", "Lassoued", "Latreche", "Layachi", "Lazrag",
    "Madani", "Mahdi", "Mahfoud", "Makdisi", "Makhlouf", "Malki", "Mami", "Mansouri", "Masmoudi", "Meddeb",
    "Mehdaoui", "Mekki", "Messaoudi", "Meziane", "Mihoubi", "Miled", "Mokhtar", "Mourad", "Moussaoui", "Mzali",
    "Naimi", "Najjar", "Nasri", "Nazih", "Nefzi", "Nouar", "Nouira", "Rahal", "Rahali", "Rahimi",
    "Ramadan", "Raouf", "Rebai", "Reguigui", "Rezki", "Riadh", "Ridha", "Riahi", "Sabri", "Sadek",
    "Sadiki", "Saidi", "Sakr", "Sallami", "Salmi", "Samia", "Saoud", "Sassi", "Sbai", "Sedki",
    "Sehili", "Selim", "Sellami", "Semlali", "Shaker", "Sharif", "Slim", "Slimane", "Slimi", "Souissi",
    "Soussa", "Tabti", "Tahar", "Tahiri", "Talbi", "Tebib", "Temam", "Terki", "Tlemcani", "Toumi",
    "Trabelsi", "Wahab", "Yahia", "Yassin", "Zaafrani", "Zabli", "Zafar", "Zahi", "Zahra", "Zaidi",
    "Zaki", "Zammit", "Zaoui", "Zara", "Zeroual", "Ziadi", "Ziani", "Zidane", "Zineddine", "Zouai",
    "Zouari", "Zoughlami", "Zribri", "Abdelli", "Achi", "Adda", "Adjal", "Affane", "Agouni", "Ait",
    "Aitouche", "Akrour", "Allouch", "Amara", "Amari", "Ameur", "Amini", "Amrouche", "Annani", "Aouar"
];

export const LAST_NAMES_SCANDINAVIAN = [
    "Andersen", "Jensen", "Nielsen", "Hansen", "Pedersen", "Rasmussen", "Christensen", "Larsen", "Olsen", "Eriksen",
    "Sorensen", "Kristensen", "Johansen", "Meyer", "Petersen", "Madsen", "Johansson", "Lindqvist", "Lindgren", "Lindberg",
    "Nilsson", "Persson", "Karlsson", "Eriksson", "Gustafsson", "Andersson", "Olsson", "Jonsson", "Hansson", "Svensson",
    "Petersson", "Bengtsson", "Magnusson", "Larsson", "Jakobsen", "Berg", "Holmberg", "Lindstrom", "Sandberg", "Nygard",
    "Stromberg", "Ekberg", "Blomqvist", "Hedlund", "Lundberg", "Sjostrom", "Engstrom", "Holmgren", "Berglund", "Lindkvist",
    "Forsberg", "Backstrom", "Nordstrom", "Hedberg", "Sjöberg", "Lindholm", "Nordin", "Strom", "Fransson", "Eklund",
    "Dahl", "Sundberg", "Haglund", "Bjork", "Hellstrom", "Vikstrom", "Nystrom", "Berggren", "Aberg", "Ekman",
    "Lundqvist", "Sundqvist", "Wahlberg", "Nord", "Lind", "Henriksson", "Ekelund", "Lindquist", "Sandqvist", "Martinsson",
    "Sjogren", "Oskarsson", "Isaksson", "Bjorklund", "Dahlberg", "Lindell", "Lundin", "Nordgren", "Oberg", "Samuelsson",
    "Bergman", "Soderlund", "Holmqvist", "Franzen", "Hedstrom", "Lindberg", "Engberg", "Norbeck", "Sundstrom", "Beckman",
    "Axelsson", "Blom", "Carlsson", "Danielsson", "Ek", "Fredriksson", "Granlund", "Hagberg", "Ivarsson", "Jonasson",
    "Kohler", "Lindahl", "Malmberg", "Nordberg", "Ostberg", "Palm", "Qvist", "Roos", "Ström", "Tornberg",
    "Ulander", "Vikberg", "Westerberg", "Zachrisson", "Ahlberg", "Bergkvist", "Cederlund", "Dahlgren", "Edberg", "Falk",
    "Grönberg", "Hallberg", "Ingvarsson", "Jansson", "Kronberg", "Lindqvist", "Molander", "Nordlund", "Ohlsson", "Paulsson",
    "Rinaldo", "Sandstrom", "Torstensson", "Utterberg", "Vinberg", "Westerlund", "Yngvesson", "Zelander", "Åkerberg", "Bergstrom",
    "Carlberg", "Davidsson", "Engstrand", "Forsman", "Grönlund", "Hellberg", "Ingmar", "Jönsson", "Käll", "Liljegren",
    "Magnusson", "Nordmark", "Ohlin", "Persson", "Qvarnstrom", "Ronningen", "Sjolander", "Tornqvist", "Ulvaeus", "Vesterberg",
    "Wennerberg", "Ylander", "Zackrisson", "Akesson", "Bengtson", "Claesson", "Davidsen", "Einarsson", "Finnsson", "Gunnarsson",
    "Helgason", "Ingolfsson", "Jonassen", "Kristjansson", "Leifsson", "Magnusson", "Njord", "Olafsson", "Palsson", "Ragnarsson",
    "Sigurdsson", "Thorsson", "Ulfsson", "Vilhjalmsson", "Westman", "Yngvar", "Øberg", "Aaberg", "Berntsen", "Christiansen",
    "Dybdahl", "Egeland", "Fossen", "Gulliksen", "Hauge", "Iversen", "Johnsen", "Knutsen", "Lunde", "Moen",
    "Norheim", "Osmundsen", "Paulsen", "Reiersen", "Solberg", "Thomassen", "Ulriksen", "Vikane", "Wold", "Ytre",
    "Aas", "Bakken", "Carlsen", "Dahl", "Eide", "Fjeld", "Gundersen", "Halvorsen", "Jakobsen", "Kristiansen",
    "Larssen", "Martinsen", "Nilssen", "Olsen", "Pettersen", "Rasmussen", "Sandnes", "Tangen", "Undheim", "Valle",
    "Wiik", "Øyen", "Ås", "Bakke", "Christoffersen", "Danielsen", "Ellingsen", "Fredriksen", "Gustavsen", "Haugen",
    "Ingebrigtsen", "Jacobsen", "Kleven", "Lorentzen", "Mathisen", "Nguyen", "Olaisen", "Pedersen", "Robertsen", "Stensrud",
    "Torkildsen", "Ulven", "Vestby", "Waage", "Østby", "Aanes", "Brenden", "Christensen", "Duus", "Engelsen",
    "Flaten", "Gjerde", "Helland", "Ivar", "Jentoft", "Kleppe", "Lindstad", "Melby", "Nessa", "Odden",
    "Presthus", "Rønning", "Skoglund", "Torgersen", "Utne", "Vangen", "Westgaard", "Ytterstad", "Zahl", "Aase",
    "Brekke", "Collett", "Dybvig", "Eknes", "Fure", "Gilje", "Hagen", "Indrehus", "Jørgensen", "Kjeldsberg"
];

export const LAST_NAMES_EASTERN_EUROPEAN = [
    "Ivanov", "Smirnov", "Kuznetsov", "Popov", "Sokolov", "Lebedev", "Kozlov", "Novikov", "Morozov", "Petrov",
    "Volkov", "Solovyov", "Vasilyev", "Zaitsev", "Pavlov", "Semyonov", "Golubev", "Vinogradov", "Bogdanov", "Vorobyov",
    "Fyodorov", "Mikhailov", "Belyaev", "Tarasov", "Belov", "Komarov", "Orlov", "Kiselev", "Makarov", "Andreev",
    "Kovalev", "Ilyin", "Gusev", "Titov", "Kuzmin", "Kudryavtsev", "Baranov", "Kulikov", "Alekseev", "Stepanov",
    "Yakovlev", "Sorokin", "Sergeev", "Romanov", "Zakharov", "Borisov", "Korolev", "Gerasimov", "Ponomarev", "Grigoryev",
    "Lazarev", "Medvedev", "Ershov", "Nikitin", "Sobolov", "Ryabov", "Polyakov", "Tsvetkov", "Danilov", "Zhukov",
    "Frolov", "Zhuravlyov", "Nikolaev", "Krylov", "Maximov", "Sidorov", "Osipov", "Belousov", "Fedotov", "Dorofeev",
    "Egorov", "Matveev", "Bobrov", "Dmitriev", "Kalinin", "Anisimov", "Petuhov", "Antanov", "Timofeev", "Nikiforov",
    "Wisniewski", "Wojciechowski", "Kowalczyk", "Kaminski", "Lewandowski", "Zielinski", "Szymanski", "Wozniak", "Dąbrowski", "Kozlowski",
    "Jankowski", "Mazur", "Wojcik", "Kwiatkowski", "Krawczyk", "Piotrowski", "Grabowski", "Nowakowski", "Pawlowski", "Michalski",
    "Adamski", "Dudek", "Zając", "Wieczorek", "Jabłonski", "Król", "Majewski", "Olszewski", "Jaworski", "Wróbel",
    "Malinowski", "Pawlak", "Witkowski", "Walczak", "Stępień", "Gorski", "Rutkowski", "Michalak", "Sikora", "Ostrowski",
    "Petrović", "Jovanović", "Nikolić", "Marković", "Đorđević", "Stojanović", "Ilić", "Stanković", "Pavlović", "Milošević",
    "Tomić", "Živković", "Kostić", "Kovačević", "Lukić", "Popović", "Simić", "Radovanović", "Savić", "Matić",
    "Đukić", "Milenković", "Lazić", "Ristić", "Joksimović", "Milojević", "Bogdanović", "Zdravković", "Mišković", "Rakić",
    "Ionescu", "Popescu", "Popa", "Dumitrescu", "Stan", "Stoica", "Gheorghe", "Rusu", "Munteanu", "Matei",
    "Stanescu", "Marinescu", "Nistor", "Voicu", "Stefanescu", "Lazar", "Marin", "Florea", "Cojocaru", "Barbu",
    "Novak", "Horvat", "Kovač", "Babić", "Marić", "Jurić", "Vuković", "Blažević", "Knežević", "Raguž",
    "Matić", "Perić", "Tomić", "Šimić", "Mandić", "Pavić", "Živković", "Barišić", "Šarić", "Radić",
    "Stoychev", "Dimitrov", "Petkov", "Georgiev", "Todorov", "Nikolov", "Ivanova", "Stoyanov", "Angelov", "Vasilev",
    "Kolev", "Marinov", "Hristov", "Mladenov", "Stefanov", "Iliev", "Dimov", "Yordanov", "Rangelov", "Atanasov",
    "Kostadinov", "Georgiev", "Karakashev", "Krastev", "Petrosyan", "Harutyunyan", "Grigoryan", "Sargsyan", "Hovhannisyan", "Manukyan",
    "Poghosyan", "Abrahamyan", "Martirosyan", "Gevorgyan", "Avetisyan", "Sahakyan", "Hakobyan", "Davidyan", "Karapetyan", "Gasparyan",
    "Mkrtchyan", "Babayan", "Vardanyan", "Stepanyan", "Navasartyan", "Melkumyan", "Galstyan", "Asatryan", "Khachatryan", "Yeghiazaryan",
    "Shevchenko", "Melnyk", "Bondarenko", "Tkachenko", "Kovalenko", "Boyko", "Lysenko", "Marchenko", "Petrenko", "Kravchenko",
    "Savchenko", "Pavlenko", "Sydorenko", "Polishchuk", "Moroz", "Shved", "Bondar", "Tymoshenko", "Kravchuk", "Marchuk",
    "Fedorenko", "Gavrilenko", "Rudenko", "Hrytsenko", "Ivanenko", "Makarenko", "Tarasenko", "Chernysh", "Yurchenko", "Zaytsev",
    "Panchenko", "Danylenko", "Vasylenko", "Omelchenko", "Nesterenko", "Mishchenko", "Klymenko", "Romanenko", "Zinchenko", "Matvienko",
    "Nazarenko", "Prokopenko", "Kostenko", "Tkachuk", "Kuzyk", "Lytvynenko", "Doroshenko", "Kalinichenko", "Honcharenko", "Bohachenko",
    "Ivanchenko", "Ivashenko", "Karpenko", "Levchenko", "Nykolayenko", "Pylypenko", "Riabchenko", "Semenchenko", "Tereshchenko", "Voitenko"
];
