// Last names - Italian/French/Portuguese/Brazilian
export const LAST_NAMES_ITALIAN = [
    "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco",
    "Bruno", "Gallo", "Conti", "De Luca", "Mancini", "Costa", "Giordano", "Rizzo", "Lombardi", "Moretti",
    "Barbieri", "Fontana", "Santoro", "Mariani", "Rinaldi", "Caruso", "Ferrara", "Galli", "Martini", "Leone",
    "Longo", "Gentile", "Martinelli", "Vitale", "Lombardo", "Serra", "Coppola", "De Santis", "D'Angelo", "Marchetti",
    "Parisi", "Villa", "Conte", "Ferraro", "Ferri", "Fabbri", "Bianco", "Marini", "Grasso", "Valentini",
    "Messina", "Sala", "De Angelis", "Gatti", "Pellegrini", "Palumbo", "Sanna", "Farina", "Rizzi", "Monti",
    "Cattaneo", "Morandi", "Silvestri", "Giuliani", "Benedetti", "Barone", "Rossetti", "Caputo", "Montanari", "Guerra",
    "Pagano", "Santini", "Orlando", "Ruggiero", "Basile", "D'Amico", "Bernardi", "Piras", "Fiore", "Amato",
    "Pellegrino", "Parodi", "Sorrentino", "Testa", "Donati", "Neri", "Grassi", "Mazza", "Palermo", "Carbone",
    "Marchese", "Piccolo", "Castelli", "Monaco", "Franchi", "Ferraro", "Melis", "Marra", "Rosati", "Sartori",
    "De Rosa", "Costantini", "D'Agostino", "Battaglia", "Piazza", "Poli", "Palma", "Damico", "Nobile", "Riva",
    "Marchi", "Moro", "Garofalo", "Mazzoni", "De Marco", "Cozzolino", "Ruggeri", "Bellini", "Giorgi", "D'Amato",
    "Ferraris", "Guarnieri", "Natale", "Rocco", "De Filippo", "Re", "Poggi", "Ranieri", "Sabatini", "Cuomo",
    "Pavan", "Valente", "Mele", "Innocenti", "Guidi", "Lucchese", "Del Vecchio", "Mauro", "Pepe", "Rosini",
    "Zanetti", "Baroni", "Pirovano", "Lorenzi", "Bartoli", "Volpe", "Mazzola", "Catalano", "Colucci", "Abate",
    "De Simone", "Castaldo", "Forte", "Di Pietro", "Masi", "Manna", "Ventura", "Arena", "Corrado", "Battaglia",
    "Basso", "Manfredi", "Mattei", "De Pasquale", "Paolicelli", "Mazzeo", "Grimaldi", "Sacco", "Ferrario", "De Martino",
    "Pinto", "Scarpa", "Turco", "Cassano", "De Giorgi", "Ferreri", "Rossini", "Nicoletti", "Romani", "Locatelli",
    "Luciani", "Perotti", "Rosa", "Zito", "Alberti", "Mazzini", "Maggio", "Negro", "Ferrante", "Pizzo",
    "Lauria", "Baldi", "Perna", "Lupo", "De Falco", "Biagi", "Cannavaro", "Mazza", "Giuliano", "Pastore",
    "Capuano", "Valerio", "Moroni", "Bernardini", "Barbato", "Bonetti", "Giusti", "Perrone", "De Cicco", "Carraro",
    "Mura", "Cimmino", "Mazzucco", "Ferro", "Scalia", "Pace", "Aquino", "Di Stefano", "Casella", "Orsini",
    "Donato", "Schiavone", "Vinci", "Esposito", "Petrelli", "Liguori", "De Paola", "Di Lorenzo", "Cavaliere", "Bonaparte",
    "Calabrese", "Puglisi", "De Maria", "Valenti", "Fiorini", "Gagliardi", "Capello", "Pozzi", "Maffei", "Del Piero",
    "Buffon", "Zanoni", "Picone", "Spinelli", "Orlando", "Terzi", "Rubino", "Ferretti", "Mazza", "Giannini",
    "Raimondi", "Baldini", "Mancuso", "Graziani", "Mazzella", "Torrisi", "Canale", "Migliore", "Albanese", "Capone",
    "Giuffrida", "Napolitano", "Pirlo", "Inzaghi", "Materazzi", "Zambrotta", "Candreva", "Pirri", "Nesta", "Toldo",
    "Totti", "Verratti", "Canuti", "Peruzzi", "Marchisio", "Barzagli", "Chiellini", "Immobile", "Insigne", "Jorginho",
    "Donnarumma", "Spinazzola", "Locatelli", "Barella", "Chiesa", "Bernardeschi", "Belotti", "Raspadori", "Gnonto", "Tonali",
    "Bastoni", "Acerbi", "Di Lorenzo", "Florenzi", "Bonucci", "Scamacca", "Pellegrini", "Cristante", "Zaniolo", "Frattesi"
];

export const LAST_NAMES_FRENCH = [
    "Martin", "Bernard", "Dubois", "Thomas", "Robert", "Richard", "Petit", "Durand", "Leroy", "Moreau",
    "Simon", "Laurent", "Lefebvre", "Michel", "Garcia", "David", "Bertrand", "Roux", "Vincent", "Fournier",
    "Morel", "Girard", "Andre", "Mercier", "Dupont", "Lambert", "Bonnet", "Francois", "Martinez", "Legrand",
    "Garnier", "Faure", "Rousseau", "Blanc", "Guerin", "Muller", "Henry", "Roussel", "Nicolas", "Perrin",
    "Morin", "Mathieu", "Clement", "Gauthier", "Dumont", "Lopez", "Fontaine", "Chevalier", "Robin", "Masson",
    "Sanchez", "Gerard", "Nguyen", "Boyer", "Denis", "Lemaire", "Duval", "Joly", "Gautier", "Roger",
    "Roche", "Roy", "Noel", "Meyer", "Lucas", "Meunier", "Jean", "Perez", "Marchand", "Dufour",
    "Blanchard", "Marie", "Barbier", "Brun", "Dumas", "Brunet", "Schmitt", "Leroux", "Colin", "Fernandez",
    "Pierre", "Renault", "Arnaud", "Rolland", "Caron", "Aubert", "Giraud", "Leclerc", "Vidal", "Boucher",
    "Gaillard", "Chev alier", "Renard", "Adam", "Poirier", "Berger", "Jacquet", "Fabre", "Royer", "Rey",
    "Perrot", "Huet", "Barre", "Guyot", "Sauvage", "Marty", "Guillaume", "Collet", "Cousin", "Legrand",
    "Riviere", "Le Gall", "Klein", "Hernandez", "Moulin", "Le Roux", "Lemoine", "Benoit", "Etienne", "Bourgeois",
    "Brossard", "Descamps", "Roques", "Chauvin", "Laporte", "Pasquier", "Lecomte", "Aubry", "Delorme", "Bouquet",
    "Chartier", "Alexandre", "Pichon", "Carpentier", "Deschamps", "Hubert", "Lefevre", "Hamel", "Dupuis", "Langlois",
    "Picard", "Regnier", "Philippe", "Germain", "Lacroix", "Prevost", "Didier", "Bazin", "Poulain", "Brunel",
    "Paul", "Vasseur", "Gimenez", "Charles", "Rodriguez", "Guillot", "Gosselin", "Lejeune", "Masse", "Vallee",
    "Cordier", "Pages", "Gilles", "Leclercq", "Boutin", "Seguin", "Thibault", "Jacob", "Bertin", "Pelletier",
    "Collin", "Herve", "Vaillant", "Barbe", "Marion", "Navarro", "Lamy", "Leduc", "Buisson", "Lacombe",
    "Lelievre", "Blanchet", "Raynaud", "Monnier", "Guillet", "Boulay", "Raymond", "Breton", "Coulon", "Tessier",
    "Lesage", "Chevrier", "Tanguy", "Bouvier", "Perrier", "Verdier", "Pasquier", "Laborde", "Monnet", "Daniel",
    "Giroux", "Godin", "Toussaint", "Humbert", "Camus", "Fernandes", "Pruvost", "Delannoy", "Imbert", "Favier",
    "Besson", "Lebreton", "Voisin", "Couturier", "Pottier", "Gros", "Pons", "Launay", "Mary", "Besnard",
    "Thebault", "Jourdain", "Blot", "Chatelain", "Devaux", "Parent", "Pineau", "Maury", "Bigot", "Duhamel",
    "Lagarde", "Salmon", "Nathalie", "Guillemot", "Charpentier", "Ruiz", "Chabaud", "Dupre", "Gaultier", "Riou",
    "Maillard", "Delon", "Renaud", "Lemaitre", "Hardy", "Fleury", "Jacques", "Maillot", "Baron", "Perret",
    "Dion", "Thierry", "Jouve", "Marquet", "Louis", "Allard", "Vallet", "Lebrun", "Mignot", "Bailly",
    "Bellanger", "Pillon", "Godard", "Guilbert", "Davy", "Michaud", "Joubert", "Gilbert", "Jullien", "Hamon",
    "Menard", "Gaudin", "Andrieu", "Guedon", "Paquin", "Boulanger", "Grandin", "Labbe", "Lombard", "Cadet",
    "Maron", "Leblanc", "Delahaye", "Bourdon", "Quentin", "Bonneau", "Gaucher", "Michon", "Drouet", "Laine",
    "Bouchard", "Girardot", "Ferrand", "Maurin", "Guyon", "Hoareau", "Ricard", "Guigon", "Bourget", "Desjardins"
];

export const LAST_NAMES_PORTUGUESE = [
    "Silva", "Santos", "Ferreira", "Pereira", "Oliveira", "Costa", "Rodrigues", "Martins", "Jesus", "Sousa",
    "Fernandes", "Goncalves", "Gomes", "Lopes", "Marques", "Alves", "Almeida", "Ribeiro", "Pinto", "Carvalho",
    "Teixeira", "Moreira", "Correia", "Mendes", "Nunes", "Soares", "Vieira", "Monteiro", "Cardoso", "Rocha",
    "Matos", "Campos", "Henriques", "Ramos", "Freitas", "Esteves", "Machado", "Barbosa", "Pires", "Melo",
    "Moura", "Tavares", "Fonseca", "Antunes", "Reis", "Leite", "Azevedo", "Simoes", "Batista", "Figueiredo",
    "Castro", "Dias", "Vaz", "Lourenco", "Neves", "Miranda", "Faria", "Duarte", "Borges", "Magalhaes",
    "Coelho", "Brito", "Ferraz", "Cunha", "Carneiro", "Morais", "Andrade", "Amorim", "Domingues", "Guerreiro",
    "Amaral", "Gaspar", "Nogueira", "Pacheco", "Matias", "Mota", "Furtado", "Valente", "Barata", "Barros",
    "Macedo", "Mesquita", "Pinheiro", "Vicente", "Afonso", "Abreu", "Medeiros", "Branco", "Lucas", "Paiva",
    "Nascimento", "Ventura", "Sequeira", "Gloria", "Bento", "Salgado", "Saraiva", "Rosa", "Cruz", "Vicente",
    "Quaresma", "Cabral", "Pinho", "Aguiar", "Neto", "Assuncao", "Serra", "Pombo", "Simao", "Patrício",
    "Furtado", "Veiga", "Chaves", "Bastos", "Caetano", "Jorge", "Sardinha", "Anjos", "Silveira", "Dantas",
    "Felix", "Fontes", "Sacramento", "Peixoto", "Seabra", "Couto", "Bernardes", "Gouveia", "Teles", "Maia",
    "Bettencourt", "Lacerda", "Varela", "Brandao", "Freire", "Leal", "Patricio", "Lago", "Seixas", "Assis",
    "Albuquerque", "Proenca", "Morado", "Portela", "Vidal", "Graca", "Braga", "Queiros", "Vargas", "Loureiro",
    "Corte-Real", "Carmona", "Torres", "Valente", "Godinho", "Passos", "Marinho", "Raposo", "Mendonca", "Rangel",
    "Pina", "Quental", "Torga", "Sarmento", "Malheiro", "Sampaio", "Bessa", "Candido", "Parreira", "Coimbra",
    "Fontoura", "Palmeira", "Araújo", "Franco", "Trindade", "Conceicao", "Pita", "Balsemao", "Real", "Pratas",
    "Pio", "Albino", "Formiga", "Cruzeiro", "Barreira", "Castanheira", "Fraga", "Horta", "Manso", "Parente",
    "Pessoa", "Rico", "Silveira", "Valle", "Veríssimo", "Albuquerque", "Amado", "Bandeira", "Barreto", "Cabeçadas",
    "Calado", "Camões", "Canto", "Carreira", "Castelo", "Cerqueira", "Chagas", "Cidade", "Correia", "Coutinho",
    "Diniz", "Espírito Santo", "Evangelista", "Falcão", "Fialho", "Forte", "Galvão", "Ginja", "Guedes", "Helder",
    "Janeiro", "José", "Lencastre", "Lisboa", "Lobato", "Lourdes", "Madeira", "Magro", "Malta", "Margarido",
    "Martinho", "Mata", "Milho", "Monsanto", "Moreio", "Mourinho", "Nassau", "Noronha", "Olivéirus", "Osório",
    "Pavao", "Pena", "Peralta", "Pestana", "Pilão", "Poeta", "Porto", "Quelhas", "Ramalho", "Rebocho",
    "Regadas", "Rodrigo", "Roma", "Rosado", "Saavedra", "Sacadura", "Santiago", "São", "Soeiro", "Sobral",
    "Souto", "Taborda", "Taveira", "Teodoro", "Tierno", "Torcato", "Travassos", "Trigueiro", "Tropa", "Tudela",
    "Vasconcelos", "Vasques", "Veloso", "Verdelho", "Vermelho", "Vilela", "Vilhena", "Xavier", "Xavior", "Ximenes",
    "Zambujal", "Zeferino", "Zenha", "Zúquete", "Abranches", "Açores", "Adães", "Agostinho", "Aguia", "Albernaz",
    "Alexandrino", "Alface", "Almendra", "Almiro", "Altino", "Álvaro", "Amaro", "Ameixa", "Anselmo", "Aprigio"
];

export const LAST_NAMES_BRAZILIAN = [
    "Silva", "Santos", "Oliveira", "Souza", "Rodrigues", "Ferreira", "Alves", "Pereira", "Lima", "Gomes",
    "Costa", "Ribeiro", "Martins", "Carvalho", "Rocha", "Almeida", "Nascimento", "Araujo", "Melo", "Barbosa",
    "Cardoso", "Reis", "Castro", "Pinto", "Cunha", "Batista", "Correia", "Ramos", "Fernandes", "Soares",
    "Vieira", "Andrade", "Nunes", "Montenegro", "Lopes", "Moreira", "Monteiro", "Freitas", "Teixeira", "Dias",
    "Campos", "Moraes", "Neves", "Borges", "Mendes", "Azevedo", "Farias", "Sales", "Xavier", "Nogueira",
    "Barros", "Leite", "Machado", "Pires", "Marques", "Vieira", "Tavares", "Leal", "Dantas", "Vargas",
    "Duarte", "Medeiros", "Cavalcante", "Filho", "Aguiar", "Fonseca", "Sampaio", "Viana", "Bezerra", "Brito",
    "Macedo", "Pacheco", "Matos", "Cabral", "Braga", "Simoes", "Carneiro", "Coutinho", "Abreu", "Fontes",
    "Amorim", "Assis", "Antunes", "Barreto", "Braz", "Couto", "Cruz", "Esteves", "Gaspar", "Guedes",
    "Henriques", "Jardim", "Magalhaes", "Matias", "Paiva", "Pimentel", "Queiroz", "Rosa", "Sa", "Vaz",
    "Amaral", "Bomfim", "Bruno", "Cerqueira", "Damasceno", "Dória", "Franco", "Guimaraes", "Holanda", "Ibiapino",
    "Jacinto", "Lago", "Maia", "Moura", "Nóbrega", "Padilha", "Portela", "Ramalho", "Saldanha", "Trindade",
    "Valle", "Zanatta", "Alencar", "Bandeira", "Coelho", "Delgado", "Evangelista", "Figueira", "Gouveia", "Honório",
    "Junqueira", "Lacerda", "Mesquita", "Nolasco", "Ornelas", "Proença", "Quaresma", "Resende", "Serafim", "Travassos",
    "Urbano", "Veloso", "Wagner", "Yuri", "Zanini", "Amaro", "Batata", "Canuto", "Dornelles", "Felix",
    "Galvao", "Herminio", "Inacio", "Januario", "Kilmer", "Loureiro", "Madureira", "Nazario", "Osório", "Palmeira",
    "Quintino", "Rangel", "Sardinha", "Teodoro", "Ulhoa", "Vasconcelos", "Willian", "Xenofonte", "Yasuda", "Zamora",
    "Aguera", "Barradas", "Calixto", "Davi", "Estrada", "Fróes", "Gomes", "Heitor", "Isaías", "Jordao",
    "Kruger", "Leonardo", "Maciel", "Napoleao", "Olímpio", "Pinheiro", "Quintela", "Romao", "Santana", "Thiago",
    "Uchoa", "Vilela", "Werneck", "Xisto", "Yamamoto", "Zagallo", "Adriano", "Bernardes", "Cesario", "Dourado",
    "Elias", "Floriano", "Ganso", "Hilário", "Irene", "Juliao", "Kaiser", "Lobo", "Medina", "Nery",
    "Otávio", "Policarpo", "Rui", "Salas", "Tenório", "Ueda", "Venâncio", "Wellington", "Ximenes", "Yago",
    "Zago", "Alexandrino", "Brandao", "Claudio", "Dionisio", "Evaristo", "Fagundes", "Gentil", "Horácio", "Ivan",
    "Jaguaribe", "Klabin", "Lázaro", "Maluf", "Nabuco", "Octávio", "Piquet", "Queróz", "Reimão", "Sabino",
    "Tasso", "Ulysses", "Valença", "Wilson", "Xanxerê", "Yabiku", "Zorzi", "Arnaldo", "Bulhoes", "Cavalcanti",
    "Dondinho", "Edilson", "Fittipaldi", "Gilberto", "Hamilton", "Igor", "Joao", "Kaveri", "Lino", "Maranhao",
    "Novaes", "Ozório", "Pele", "Querino", "Ronaldo", "Socrates", "Tostao", "Ubiratan", "Vivaldo", "Wendell",
    "Xande", "Yolanda", "Zico", "Alisson", "Becker", "Cássio", "Dida", "Edmundo", "Fabinho", "Gustavo",
    "Hulk", "Ibson", "Juninho", "Kaká", "Lucas", "Marcelo", "Neymar", "Oscar", "Paulinho", "Rafael",
    "Robinho", "Thiago", "Vitor", "Willian", "Gabigol", "Jesus", "Firmino", "Richarlison", "Raphinha", "Antony"
];
