// Last names - Greek and African
export const LAST_NAMES_GREEK = [
    "Papadopoulos", "Vlachos", "Angelopoulos", "Nikolaidis", "Georgiou", "Dimitriadis", "Pappas", "Karagiannis", "Makris", "Christodoulou",
    "Oikonomou", "Konstantinou", "Michalopoulos", "Bakoyannis", "Samaras", "Tsipras", "Karamanlis", "Papandreou", "Mitsotakis", "Venizelos",
    "Antonopoulos", "Athanasiadis", "Alexopoulos", "Andreadis", "Andreopoulos", "Athanasiou", "Balaskas", "Charalampous", "Christopoulos", "Daskalakis",
    "Dimopoulos", "Drakos", "Efthymiou", "Evangelou", "Fotopoulos", "Galanopoulos", "Georgiadis", "Giannopoulos", "Giannakis", "Gkiokas",
    "Grigoropoulos", "Hatzis", "Ioannidis", "Ioannou", "Kalogeropoulos", "Kalogirou", "Kapetanakis", "Karakatsanis", "Karalis", "Katsaros",
    "Kavvadas", "Kazakos", "Kefalogianni", "Kitsios", "Kokkinos", "Kollias", "Kondos", "Kontogiannis", "Kostopoulos", "Kotsifakis",
    "Kouroumblis", "Koutsoukos", "Kyriakidis", "Kyriakou", "Lamprou", "Lazaridis", "Leontidis", "Liapis", "Logaras", "Loukas",
    "Lykos", "Mandras", "Maniatis", "Markopoulos", "Mavromatis", "Melis", "Mitsios", "Mitsopoulos", "Moustakas", "Mpakolas",
    "Nikolaou", "Papadakis", "Papakonstantinou", "Papanikos", "Papatheodorou", "Papazoglou", "Paraskevopoulos", "Paschos", "Pavlidis", "Pavlopoulos",
    "Perakis", "Petridis", "Petropoulos", "Politis", "Poulios", "Psarras", "Raptis", "Roussos", "Sakellaridis", "Sakellaropoulos",
    "Sarris", "Simonidis", "Skouras", "Solomos", "Sotiropoulos", "Spanos", "Spinellis", "Stamatatos", "Stamatiou", "Stathis",
    "Stavropoulos", "Stefanopoulos", "Symeonidis", "Terzis", "Theodoridis", "Theodoropoulos", "Theofilopoulos", "Topalis", "Triandafyllidis", "Triantafillopoulos",
    "Tsagarakis", "Tsaousis", "Tsatsos", "Tsekouras", "Tsigaridis", "Tsiknakis", "Tsolakidis", "Tsoukalas", "Tzanetatos", "Tzannis",
    "Vafeiadis", "Vasilopoulos", "Venetis", "Vlahakis", "Voglis", "Voulgaris", "Xanthopoulos", "Zacharatos", "Zachariadis", "Zafiris",
    "Zafiropoulos", "Zahos", "Zervas", "Zikaridis", "Zikos", "Zisis", "Zouras", "Adamidis", "Aggelidis", "Aggelou",
    "Agorastos", "Alexakis", "Alivizatos", "Alvanou", "Amanatidis", "Anastasakis", "Anastasiadis", "Anastopoulos", "Andreou", "Andronikou",
    "Angelakis", "Angelidou", "Antzoulatou", "Apostolidis", "Apostolou", "Argyriou", "Argyropoulos", "Arnaoutoglou", "Artemakis", "Artemiou",
    "Aslanidis", "Asteriou", "Athanasiadou", "Avgousti", "Bakalakos", "Bakirtzis", "Balabanis", "Balaouras", "Baltazis", "Bambakidis",
    "Baxevanis", "Baxevanos", "Bechrakis", "Bekiris", "Belokas", "Bezas", "Bitsakos", "Bitsanis", "Blionas", "Bogiatzoglou",
    "Bonis", "Boras", "Botsis", "Bouloukos", "Bournazos", "Boutaris", "Bouzianis", "Bratsos", "Chalkidis", "Chalkos",
    "Chamalidis", "Charalambidis", "Charalampidis", "Chatzigeorgiou", "Chatzikonstantinou", "Chatzinikolaou", "Chatzitheodorou", "Chatzopoulos", "Cheliotis", "Chondros",
    "Christakis", "Christodoulakis", "Christoforakis", "Christoforidis", "Chrysanthakis", "Chrysikos", "Chrysomallis", "Chrysopoulos", "Dagdilelis", "Dalaklis",
    "Dalambiras", "Damaskos", "Danaos", "Dandis", "Daniilidis", "Danikas", "Dareiou", "Davradakis", "Delis", "Dellis",
    "Demetriou", "Dermitzakis", "Diakogiannis", "Diakos", "Diamantakis", "Diamantidis", "Diamantopoulos", "Dimakopoulos", "Dimakos", "Dimitrakakis",
    "Dimitrakis", "Dimitriou", "Dinakis", "Dionasios", "Doukakis", "Doukas", "Doulamis", "Dounias", "Drougas", "Droulias",
    "Drossos", "Efstathiou", "Efstratiou", "Eleftheriadis", "Eleftheriou", "Emmanouilidis", "Emmanouil", "Epitropakis", "Euthymiou", "Exarchos",
    "Faklaris", "Falireas", "Famelis", "Fanariotis", "Fasoulas", "Fatouros", "Filis", "Filippidis", "Filippou", "Fiorakis",
    "Flevotomos", "Florakis", "Forakis", "Fotiadis", "Fotiou", "Fourlas", "Fragulis", "Fragoulis", "Frangopoulos", "Frangoulis",
    "Fytros", "Gaganis", "Gaitanis", "Gakis", "Galanakis", "Galanos", "Galatoulas", "Galetakis", "Galinos", "Galios",
    "Gantzou", "Gardelis", "Gavalas", "Gavriil", "Gazis", "Geladas", "Gemenetzis", "Gennimatas", "Georgakis", "Georgas"
];

export const LAST_NAMES_AFRICAN = [
    "Diallo", "Diop", "Traore", "Toure", "Keita", "Konate", "Camara", "Cisse", "Dembele", "Bamba",
    "Sangare", "Sow", "Koulibaly", "Mendy", "Sarr", "Gueye", "Ndoye", "Kane", "Niang", "Ba",
    "Fall", "Sy", "Sane", "Dieng", "Ndiaye", "Mbaye", "Faye", "Thiam", "Diaw", "Dia",
    "Sylla", "Bakayoko", "Kone", "Coulibaly", "Bolou", "Gbagbo", "Ouattara", "Bony", "Kalou", "Gradel",
    "Gervinho", "Drogba", "Eboue", "Zokora", "Kolo", "Yaya", "Aurier", "Bailly", "Cornet", "Pepe",
    "Salif", "Serge", "Jean-Pierre", "Max", "Nicolas", "Emmanuel", "Samuel", "Wilfried", "Franck", "Eric",
    "Osei", "Mensah", "Asante", "Boateng", "Asamoah", "Gyan", "Ayew", "Appiah", "Essien", "Muntari",
    "Schlupp", "Wakaso", "Atsu", "Partey", "Agyemang", "Addo", "Ofori", "Amartey", "Baba", "Afriyie",
    "Osabutey", "Owusu", "Adjei", "Annan", "Adade", "Acheampong", "Edusei", "Antwi", "Bentil", "Danso",
    "Okocha", "Kanu", "Yobo", "Odemwingie", "Martins", "Ameobi", "Mikel", "Moses", "Iheanacho", "Musa",
    "Success", "Iwobi", "Ndidi", "Aina", "Ekong", "Ighalo", "Osimhen", "Chukwueze", "Aribo", "Lookman",
    "Akinfenwa", "Aluko", "Azeez", "Babalola", "Bassey", "Boniface", "Dennis", "Ebiowei", "Ejiofor", "Eze",
    "Fadaka", "Fashanu", "Femi", "Gidion", "Idowu", "Ikpeba", "Ilori", "Jimoh", "Kelechi", "Lawal",
    "Maduka", "Nnamdi", "Nwankwo", "Obafemi", "Obinna", "Ofoegbu", "Ogbonna", "Ogheneovo", "Oguike", "Okechukwu",
    "Okoro", "Okorie", "Okosun", "Ola", "Oladapo", "Olajide", "Olatunji", "Olawale", "Olise", "Onuoha",
    "Origi", "Oshodi", "Owolabi", "Oyebanjo", "Oyewole", "Sadiq", "Sanusi", "Shehu", "Shoretire", "Simon",
    "Taye", "Temitope", "Uche", "Udeze", "Ugwu", "Ukeje", "Umeh", "Usman", "Utaka", "Victor",
    "Yakubu", "Yemi", "Yusuf", "Zaka", "Beye", "Coly", "Dabo", "Fadiga", "Koite", "Lamine",
    "Ly", "Mane", "Mbodji", "Moussa", "Ndong", "Niasse", "Sagna", "Saivet", "Sakho", "Souare",
    "Tall", "Wague", "Zargo", "Aboubakar", "Bassogog", "Bedimo", "Bekale", "Chedjou", "Choupo-Moting", "Ekambi",
    "Etame", "Fai", "Idrissou", "Kameni", "M'Bia", "Makoun", "Mandjeck", "Matip", "Meyong", "Millas",
    "Moukandjo", "Ngamaleu", "Njie", "Nkoudou", "Ondo", "Ondoa", "Onguene", "Song", "Souleymanou", "Toko Ekambi",
    "Urtubi", "Webo", "Anguissa", "Nlend", "Oyongo", "Abega", "Atouba", "Bahoken", "Ebaka", "Kunde",
    "Bassonga", "Mouandje", "Kana-Biyik", "Mboma", "Nkono", "Omam-Biyik", "Bell", "Tchangai", "Djigla", "Akakpo",
    "Casimir", "Gakpe", "Koudou", "Mensah", "Omotoyossi", "Adebayor", "Agassa", "Ayite", "Dossevi", "Farnolle",
    "Gnakpa", "Malm", "Moussa", "Ouro-Akoriko", "Romao", "Salifou", "Segbefia", "Senaya", "Tchakei", "Wome",
    "Agboh", "Chakoua", "Fortes", "Gounouma", "Kader", "Mama", "Nibombe", "Olufade", "Sinzogan", "Zoukou",
    "Aboutrika", "Abdelshafi", "Ahmed", "Ali", "Barakat", "El-Gohary", "El-Hadary", "El-Khatib", "El-Sayed", "Fathy",
    "Ghaly", "Hassan", "Hosny", "Ibrahim", "Kamel", "Mido", "Mohamed", "Ramadan", "Salah", "Shehata",
    "Trezeguet", "Warda", "Zaki", "Hegazi", "Sobhi", "Elneny", "Ashour", "Gaber", "Kouka", "Marmoush"
];
