// Last names - Global/English/Spanish/German
export const LAST_NAMES_GLOBAL = [
    "Silva", "Santos", "Rodriguez", "Martinez", "Garcia", "Lopez", "Gonzalez", "Perez", "Sanchez", "Fernandez",
    "Mueller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann",
    "Johnson", "Williams", "Brown", "Jones", "Miller", "Davis", "Wilson", "Moore", "Taylor", "Anderson",
    "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Robinson", "Clark", "Lewis", "Lee",
    "Walker", "Hall", "Allen", "Young", "King", "Wright", "Scott", "Green", "Adams", "Baker",
    "Nelson", "Carter", "Mitchell", "Roberts", "Turner", "Phillips", "Campbell", "Parker", "Evans", "Edwards",
    "Collins", "Stewart", "Morris", "Rogers", "Reed", "Cook", "Morgan", "Bell", "Murphy", "Bailey",
    "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward", "Torres", "Peterson", "Gray", "Ramirez",
    "James", "Watson", "Brooks", "Kelly", "Sanders", "Price", "Bennett", "Wood", "Barnes", "Ross",
    "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long", "Patterson", "Hughes", "Flores", "Washington",
    "Butler", "Simmons", "Foster", "Bryant", "Alexander", "Russell", "Griffin", "Hayes", "Myers", "Ford",
    "Hamilton", "Graham", "Sullivan", "Wallace", "Woods", "Cole", "West", "Jordan", "Owens", "Reynolds",
    "Fisher", "Ellis", "Harrison", "Gibson", "McDonald", "Cruz", "Marshall", "Ortiz", "Gomez", "Murray",
    "Freeman", "Wells", "Webb", "Simpson", "Stevens", "Tucker", "Porter", "Hunter", "Hicks", "Crawford",
    "Henry", "Boyd", "Mason", "Morales", "Kennedy", "Warren", "Dixon", "Ramos", "Reyes", "Burns",
    "Gordon", "Shaw", "Holmes", "Rice", "Robertson", "Hunt", "Black", "Daniels", "Palmer", "Mills",
    "Alves", "Ferreira", "Oliveira", "Costa", "Cardoso", "Martins", "Carvalho", "Sousa", "Vieira", "Nunes",
    "Andersen", "Jensen", "Nielsen", "Hansen", "Pedersen", "Rasmussen", "Christensen", "Larsen", "Olsen", "Eriksen",
    "Rossi", "Russo", "Ferrari", "Esposito", "Bianchi", "Romano", "Colombo", "Ricci", "Marino", "Greco",
    "Dubois", "Moreau", "Laurent", "Simon", "Michel", "Leroy", "Roux", "David", "Bertrand", "Morel",
    "Park", "Kim", "Lee", "Choi", "Jung", "Kang", "Cho", "Yoon", "Jang", "Lim",
    "Sato", "Suzuki", "Takahashi", "Tanaka", "Watanabe", "Ito", "Yamamoto", "Nakamura", "Kobayashi", "Kato",
    "Diallo", "Traore", "Toure", "Keita", "Konate", "Camara", "Cisse", "Dembele", "Diop", "Bamba",
    "Al-Rashid", "Al-Hamad", "Hassan", "Hussein", "Ibrahim", "Mahmoud", "Said", "Khalil", "Abbas", "Mansour",
    "Papadopoulos", "Nikolaidis", "Georgiou", "Dimitriadis", "Karagiannis", "Christodoulou", "Konstantinou", "Samaras", "Vlahos", "Makris",
    "Ivanov", "Petrov", "Popov", "Novikov", "Kozlov", "Morozov", "Volkov", "Yakovlev", "Romanov", "Alekseev",
    "Johansson", "Lindqvist", "Lindgren", "Lindberg", "Nilsson", "Persson", "Karlsson", "Eriksson", "Gustafsson", "Andersson",
    "Yilmaz", "Kaya", "Demir", "Ozturk", "Aydin", "Celik", "Arslan", "Dogan", "Kilic", "Sahin",
    "Yang", "Wang", "Li", "Liu", "Chen", "Zhang", "Huang", "Zhao", "Wu", "Zhou",
    "Patel", "Shah", "Singh", "Kumar", "Sharma", "Gupta", "Reddy", "Rao", "Mishra", "Iyer"
];

export const LAST_NAMES_ENGLISH = [
    "Smith", "Johnson", "Williams", "Brown", "Jones", "Miller", "Davis", "Wilson", "Moore", "Taylor",
    "Anderson", "Thomas", "Jackson", "White", "Harris", "Martin", "Thompson", "Garcia", "Martinez", "Robinson",
    "Clark", "Rodriguez", "Lewis", "Lee", "Walker", "Hall", "Allen", "Young", "King", "Wright",
    "Scott", "Green", "Adams", "Baker", "Nelson", "Carter", "Mitchell", "Roberts", "Turner", "Phillips",
    "Campbell", "Parker", "Evans", "Edwards", "Collins", "Stewart", "Morris", "Rogers", "Reed", "Cook",
    "Morgan", "Bell", "Murphy", "Bailey", "Rivera", "Cooper", "Richardson", "Cox", "Howard", "Ward",
    "Torres", "Peterson", "Gray", "Ramirez", "James", "Watson", "Brooks", "Kelly", "Sanders", "Price",
    "Bennett", "Wood", "Barnes", "Ross", "Henderson", "Coleman", "Jenkins", "Perry", "Powell", "Long",
    "Patterson", "Hughes", "Flores", "Washington", "Butler", "Simmons", "Foster", "Bryant", "Alexander", "Russell",
    "Griffin", "Hayes", "Myers", "Ford", "Hamilton", "Graham", "Sullivan", "Wallace", "Woods", "Cole",
    "West", "Jordan", "Owens", "Reynolds", "Fisher", "Ellis", "Harrison", "Gibson", "McDonald", "Cruz",
    "Marshall", "Ortiz", "Gomez", "Murray", "Freeman", "Wells", "Webb", "Simpson", "Stevens", "Tucker",
    "Porter", "Hunter", "Hicks", "Crawford", "Henry", "Boyd", "Mason", "Kennedy", "Warren", "Dixon",
    "Burns", "Gordon", "Shaw", "Holmes", "Rice", "Robertson", "Hunt", "Black", "Daniels", "Palmer",
    "Mills", "Nichols", "Grant", "Knight", "Ferguson", "Rose", "Stone", "Hawkins", "Dunn", "Perkins",
    "Hudson", "Spencer", "Gardner", "Stephens", "Payne", "Pierce", "Berry", "Matthews", "Arnold", "Wagner",
    "Willis", "Ray", "Watkins", "Olson", "Carroll", "Duncan", "Snyder", "Hart", "Cunningham", "Bradley",
    "Lane", "Andrews", "Ruiz", "Harper", "Fox", "Riley", "Armstrong", "Carpenter", "Weaver", "Greene",
    "Lawrence", "Elliott", "Chavez", "Sims", "Austin", "Peters", "Kelley", "Franklin", "Lawson", "Fields",
    "Gutierrez", "Ryan", "Schmidt", "Carr", "Vasquez", "Castillo", "Wheeler", "Chapman", "Oliver", "Montgomery",
    "Richards", "Williamson", "Johnston", "Banks", "Meyer", "Bishop", "McCoy", "Howell", "Alvarez", "Morrison",
    "Hansen", "Fernandez", "Garza", "Harvey", "Little", "Burton", "Stanley", "Nguyen", "George", "Jacobs",
    "Reid", "Fuller", "Lynch", "Dean", "Gilbert", "Garrett", "Romero", "Welch", "Larson", "Frazier",
    "Burke", "Hanson", "Day", "Mendoza", "Moreno", "Bowman", "Medina", "Fowler", "Brewer", "Hoffman",
    "Carlson", "Silva", "Pearson", "Holland", "Douglas", "Fleming", "Jensen", "Vargas", "Byrd", "Davidson",
    "Hopkins", "May", "Terry", "Herrera", "Wade", "Soto", "Walters", "Curtis", "Neal", "Caldwell",
    "Lowe", "Jennings", "Barnett", "Graves", "Jimenez", "Horton", "Shelton", "Barrett", "Obrien", "Castro",
    "Sutton", "Gregory", "McKinney", "Lucas", "Miles", "Craig", "Rodriquez", "Chambers", "Holt", "Lambert",
    "Fletcher", "Watts", "Bates", "Hale", "Rhodes", "Pena", "Beck", "Newman", "Haynes", "McDaniel",
    "Mendez", "Bush", "Vaughn", "Parks", "Dawson", "Santiago", "Norris", "Hardy", "Love", "Steele"
];

export const LAST_NAMES_SPANISH = [
    "Garcia", "Rodriguez", "Martinez", "Lopez", "Gonzalez", "Hernandez", "Perez", "Sanchez", "Ramirez", "Torres",
    "Flores", "Rivera", "Gomez", "Diaz", "Cruz", "Morales", "Reyes", "Jimenez", "Alvarez", "Ruiz",
    "Castillo", "Romero", "Gutierrez", "Ortiz", "Mendoza", "Moreno", "Medina", "Vargas", "Ramos", "Chavez",
    "Herrera", "Fernandez", "Delgado", "Vasquez", "Navarro", "Aguilar", "Castro", "Guerrero", "Campos", "Vega",
    "Nunez", "Espinoza", "Dominguez", "Santos", "Sandoval", "Rojas", "Valencia", "Mendez", "Luna", "Salazar",
    "Contreras", "Soto", "Cabrera", "Molina", "Estrada", "Acosta", "Silva", "Fuentes", "Padilla", "Villanueva",
    "Cervantes", "Orozco", "Ochoa", "Santiago", "Pena", "Cortes", "Rios", "Ayala", "Ibarra", "Suarez",
    "Carrillo", "Guzman", "Mejia", "Leon", "Velasquez", "Figueroa", "Marquez", "Franco", "Serrano", "Aquino",
    "Lara", "Duarte", "Ponce", "Miranda", "Trujillo", "Bautista", "Alvarado", "Pacheco", "Solis", "Valdez",
    "Vera", "Gallegos", "Escobar", "Villanueva", "Rosales", "Cano", "Cardenas", "Huerta", "Montes", "Benitez",
    "Roman", "Gallardo", "Bermudez", "Villalobos", "Maldonado", "Lozano", "Arellano", "Barrera", "Munoz", "Arias",
    "Camacho", "Nieto", "Cordero", "Valenzuela", "Zuniga", "Cortez", "Zavala", "Mora", "Salinas", "Galvan",
    "Macias", "Rubio", "Pineda", "Nava", "Avila", "Santana", "Cisneros", "Zamora", "Duran", "Cantu",
    "Rico", "Quintana", "Sotelo", "Calderon", "Montoya", "Jaramillo", "Carrasco", "Tapia", "Quintero", "Villegas",
    "Espinosa", "Velazquez", "Orellana", "Tovar", "Palacios", "Cordova", "Coronado", "Arroyo", "Parra", "Peralta",
    "Moran", "Bonilla", "Olvera", "Barrientos", "Saucedo", "Olivares", "Beltran", "Rangel", "Solano", "Argueta",
    "Bustamante", "Valdes", "Urbina", "Santillan", "Camarena", "Linares", "Vergara", "Rosado", "Madrigal", "Guevara",
    "Elizondo", "Esquivel", "Barrios", "Grijalva", "Caballero", "Resendiz", "Lemus", "Ornelas", "Zepeda", "Rivas",
    "Banda", "Corrales", "De La Cruz", "Villagomez", "Cuevas", "Mercado", "Del Rio", "Robles", "Alonso", "Del Valle",
    "Meza", "Trejo", "Aparicio", "Baez", "Prado", "Zarate", "De Leon", "Prieto", "Montalvo", "Arreola",
    "Bueno", "Renteria", "Becerra", "Aleman", "Melendez", "Trevino", "Arredondo", "Escobedo", "Garibay", "Alcala",
    "Nolasco", "Casas", "Tellez", "Alcaraz", "Cornejo", "De La Rosa", "Real", "Paz", "Bravo", "Velasco",
    "Segura", "Montano", "Leal", "Navarrete", "Andrade", "Oviedo", "Lugo", "Palma", "Osorio", "Salvador",
    "Salas", "Portillo", "Aguayo", "Olivera", "Pulido", "Cardona", "Cienfuegos", "Toledo", "Ventura", "Solorio",
    "De Los Santos", "Aranda", "Altamirano", "Venegas", "Partida", "Varela", "Escalante", "Jaime", "Barragan", "Chapa",
    "Galindo", "Correa", "De Jesus", "Lomeli", "Magana", "Murillo", "Castaneda", "Tejeda", "Gamez", "Garay",
    "Garnica", "Godinez", "Islas", "Landeros", "Lorenzana", "Lua", "Manriquez", "Ocampo", "Ontiveros", "Pantoja",
    "Pizarro", "Porras", "Quezada", "Regalado", "Reynoso", "Ruelas", "Saavedra", "Serafin", "Sevilla", "Somoza",
    "Tamayo", "Terrazas", "Tinoco", "Topete", "Uribe", "Velarde", "Vidaurri", "Villalpando", "Villarreal", "Vizcarra",
    "Yanez", "Zapatero", "Zapata", "Zigala", "Zorrilla", "Zuniga", "Acevedo", "Adrian", "Aguilera", "Almaguer"
];

export const LAST_NAMES_GERMAN = [
    "Mueller", "Schmidt", "Schneider", "Fischer", "Weber", "Meyer", "Wagner", "Becker", "Schulz", "Hoffmann",
    "Schaefer", "Koch", "Bauer", "Richter", "Klein", "Wolf", "Schroeder", "Neumann", "Schwarz", "Zimmermann",
    "Braun", "Krueger", "Hartmann", "Lange", "Werner", "Schmitz", "Krause", "Meier", "Lehmann", "Schmid",
    "Schulze", "Maier", "Koehler", "Herrmann", "Koenig", "Walter", "Mayer", "Huber", "Kaiser", "Fuchs",
    "Peters", "Lang", "Scholz", "Moller", "Weiss", "Jung", "Hahn", "Schubert", "Vogel", "Friedrich",
    "Keller", "Guenther", "Frank", "Berger", "Winkler", "Roth", "Beck", "Lorenz", "Baumann", "Franke",
    "Albrecht", "Schuster", "Simon", "Ludwig", "Boehm", "Winter", "Kraus", "Martin", "Schumacher", "Kraemer",
    "Vogt", "Stein", "Sommer", "Haas", "Graf", "Heinrich", "Seidel", "Brandt", "Schreiber", "Pietsch",
    "Dietrich", "Ziegler", "Kuhn", "Kuehn", "Pohl", "Engel", "Horn", "Busch", "Bergmann", "Thomas",
    "Voigt", "Sauer", "Arnold", "Wolff", "Pfeiffer", "Janssen", "Jansen", "Bosch", "Hansen", "Zander",
    "Hermann", "Hess", "Jaeger", "Schilling", "Adam", "Otto", "Kramer", "Haase", "Schiller", "Grimm",
    "Lenz", "Ritter", "Schade", "Block", "Erdmann", "Lindner", "Seifert", "Wendt", "Kessler", "Brueckner",
    "Ernst", "Witte", "Paul", "Bartsch", "Feldmann", "Thiel", "Schlegel", "Beckmann", "Wiegand", "Bertram",
    "Baer", "Noack", "Ebert", "Fritsch", "Hildebrandt", "Gruber", "Eckert", "Marx", "Heinz", "Probst",
    "Kessel", "Ullrich", "Hess", "Thiele", "Bock", "Boehme", "Kopp", "Heine", "Engelhardt", "Lindemann",
    "Geiger", "Oswald", "Kuhlmann", "Funke", "Koerner", "Ott", "Kraft", "Kunze", "Goetz", "Eichler",
    "Hoppe", "Henkel", "Steiner", "Scharf", "Buchholz", "Frey", "Brand", "Naumann", "Kunz", "Buettner",
    "Schramm", "Ullmann", "Wulff", "Rupp", "Fink", "Dorn", "Hauck", "Schwabe", "Burger", "Wieland",
    "Strauss", "Kellner", "Wenzel", "Klemm", "Falk", "Ahrens", "Reich", "Kroll", "Link", "Decker",
    "Heim", "Rausch", "Forster", "Springer", "Roemer", "Beyer", "Baumann", "Mertens", "Eichhorn", "Seitz",
    "Hempel", "Michel", "Hager", "Jakob", "Rau", "Seidl", "Stock", "Merz", "Rausch", "Schenk",
    "Zeller", "Wimmer", "Bachmann", "Heck", "Greiner", "Maurer", "Stoll", "Gross", "Rose", "Stark",
    "Hamann", "Kern", "Bender", "Diehl", "Wetzel", "Heise", "Holz", "Sauter", "Brinkmann", "Krug",
    "Krieger", "Auer", "Schrader", "Renner", "Brunner", "Hesse", "Vetter", "Dittrich", "Reinhardt", "Klose",
    "Kohler", "Barthel", "Bruns", "Schiffer", "Born", "Albers", "Westermann", "Kiefer", "Moser", "Sasse",
    "Kluge", "Baum", "Freund", "Herbst", "Fleischer", "Appel", "Wegner", "Steffen", "Henning", "Will",
    "Adler", "Glaser", "Dietz", "Sander", "Freitag", "Marquardt", "Knoll", "Klaus", "Rudolf", "Conrad",
    "Preuß", "Reiter", "Heinze", "Hartung", "Rudolph", "Gabriel", "Blum", "Stahl", "Schindler", "Hanke",
    "Haupt", "Unger", "Schaeffer", "Hinz", "Heyer", "Lauer", "Riedel", "Popp", "Mack", "Giese",
    "Kohl", "Scherer", "Schiller", "Reuter", "Preis", "Esser", "Stadler", "Hofer", "Kurz", "Kastner"
];
